### ISSUE TITLE
ios 17.4.1使用该方案的时候侯选字会出现部分生僻字缺失

### ISSUE THREAD

**Issue by J02Octo** [Mintimate/oh-my-rime#101]
如题，ios端会出现部分侯选字不显示的情况，请问有什么解决方法？

![IMG_5483](https://github.com/Mintimate/oh-my-rime/assets/54092818/2cff8fc6-037b-4155-b8f0-5da66f4f0775)

**Comment by Mintimate** [comment]
本质上，问题和 #86 、#74 是一样的。 也就是iOS自带的字库，没有这些字体。仓输入法可以自定义字体实现这些字的显示：
![自定义字体](https://github.com/Mintimate/oh-my-rime/assets/43734212/b78b0c16-6132-42ae-b748-66f1c06b4fee)
最终的效果：
![自定义的效果](https://github.com/Mintimate/oh-my-rime/assets/43734212/de60ffd7-839b-4d35-9e76-235740cc52ef)
