### ISSUE TITLE
windows11 重新部署后无法输入

### ISSUE THREAD

**Issue by xiaogong-li** [Mintimate/oh-my-rime#102]
用压缩包内容覆盖原有配置，重新部署后无法输入。 只能输入英文，中文状态下展示候选词也无法进行其他操作（切换等操作都无法进行）

还好备份了原来的配置…

**Comment by YummyCocoa** [comment]
无法复现，下载最新的分支文件配合小狼毫的最新每夜版本无法复现。不过这个问题，一般有两种可能：
1. 个人配置有问题，而且多数发生在Lua。
2. 小狼毫的bug，尝试重启小狼毫服务并重新部署。

**Comment by Mintimate** [comment]
Windows 11 ARM版本配合小狼毫 2024-06-06 发布的 https://github.com/rime/weasel/releases/tag/0.16.1 测试薄荷方案通过，没有无法输入的问题。
