### ISSUE TITLE
[Linux]能否修改一下英文输入的图标

### ISSUE THREAD

**Issue by LFRon** [Mintimate/oh-my-rime#107]
我发现我用RIME时,输入法内英文输入的图标太突兀了,和KDE/GNOME全局主题(不论是chromeOS样式还是Breeze原版)有些格格不入,开发者能否修改一下这个图标?谢谢!
![Screenshot_20240618_200143](https://github.com/Mintimate/oh-my-rime/assets/141307807/9d749152-808c-4269-8a2f-b6c2a71e8d26)

**Comment by Mintimate** [comment]
这个不清楚，应该是改不了的。可能在编译安装ibus-rime的时候可以在源码里改？具体没试过。

**Comment by LFRon** [comment]
> 这个不清楚，应该是改不了的。可能在编译安装ibus-rime的时候可以在源码里改？具体没试过。

啊,我是用fcitx5-rime做后端的😂

**Comment by LFRon** [comment]
> 这个不清楚，应该是改不了的。可能在编译安装ibus-rime的时候可以在源码里改？具体没试过。

这个图标我在用原版RIME时没出现,是部署了薄荷输入法之后输入法内输入英文后才发现的😂

**Comment by Mintimate** [comment]
不是薄荷设计的，看着是Fcitx5 rime自己的，或者Fcitx5的。薄荷内没有这个图标。

再准确点的话，其实小狼毫可以自定义图标，但是薄荷同样也没自定义图标。

**Comment by LFRon** [comment]
> 不是薄荷设计的，看着是Fcitx5 rime自己的，或者Fcitx5的。薄荷内没有这个图标。
> 
> 再准确点的话，其实小狼毫可以自定义图标，但是薄荷同样也没自定义图标。

原来如此,那我去RIME那边问问
