### ISSUE TITLE
按照说明配置好了输入法 打字也有对应主题了 但是输入time week date 等均未出现对应的时间和日期

### ISSUE THREAD

**Issue by github123520** [Mintimate/oh-my-rime#108]

**Comment by github123520** [comment]
是windows10 版本

**Comment by Mintimate** [comment]
中文状态输入才可以激活

**Comment by github123520** [comment]
> 中文状态输入才可以激活
<img width="310" alt="Snipaste_2024-06-19_18-45-42" src="https://github.com/Mintimate/oh-my-rime/assets/92377726/b16f3848-017c-488a-8070-3e642cc70558">
<img width="202" alt="Snipaste_2024-06-19_18-45-31" src="https://github.com/Mintimate/oh-my-rime/assets/92377726/2d8ce199-d3d6-45ba-a0bb-83a96054a3ba">
<img width="292" alt="Snipaste_2024-06-19_18-45-51" src="https://github.com/Mintimate/oh-my-rime/assets/92377726/557f8b3b-bab1-4ed5-9028-661877beacae">
就是在中文状态下的 小狼毫0.16 最新版
<img width="742" alt="Snipaste_2024-06-19_18-47-11" src="https://github.com/Mintimate/oh-my-rime/assets/92377726/64f2500a-62a0-4c71-8a69-7f33ac9cad20">

**Comment by Mintimate** [comment]
最新main分支无法复现，删除build文件夹重新部署试试
