### ISSUE TITLE
反查模块不起作用了

### ISSUE THREAD

**Issue by Unsung-dev** [Mintimate/oh-my-rime#109]
uu后面输入拼音这个用法

**Comment by Mintimate** [comment]
按住 shift 输入 U ，松开 shift 输入 u ，之后再输入拼音进行反查拆字。

**Comment by Unsung-dev** [comment]
👌 刚试了下可以，之前可以直接小写uu的  现在只能先大写U再小写u

**Comment by Mintimate** [comment]
哈哈，那看来是很久没有更新了。三个月前更新成这样的。详细可以看更新日志：[https://www.mintimate.cc/zh/changeLog/#_2024-s02]（https://www.mintimate.cc/zh/changeLog/#_2024-s02）

**Comment by Unsung-dev** [comment]
再请教一个问题，跟皮肤相关的
<img width="327" alt="image" src="https://github.com/Mintimate/oh-my-rime/assets/174196837/d4007efb-a3a0-4260-ab9b-4007a44a5897">
我标红的这部分在代码里面，哪部分可以修改下
