### ISSUE TITLE
readme里98五笔的网址已经失效

### ISSUE THREAD

**Issue by letterk** [Mintimate/oh-my-rime#113]
现在是个盗版小说网站

**Comment by Mintimate** [comment]
确实，晚点我问一下98wubi团队的小伙伴，看看是换地址还是取消官网了。

**Comment by YummyCocoa** [comment]
已经确认了，目前wubi98的网站，已经换回：[https://wubi98.github.io/](https://wubi98.github.io/)。用爱发电的项目，换回GitHub Page，不用操心太多。 只是中国大陆可能部分地区访问有点小困难。
