### ISSUE TITLE
候选框空白的问题

### ISSUE THREAD

**Issue by xcc3306** [Mintimate/oh-my-rime#115]
在这样一个场景下：
我在游戏里，打开输入框，输入内容，如果我的候选框设置的是竖排的，就很正常，但是我把我的候选框设置成横排之后，候选框从第二个到最后就都是空白的了
![image](https://github.com/user-attachments/assets/b1ca3193-f0e2-4148-8848-b0fd84e8904f)
这是我把候选框设置成横排的，之后遇到的问题
![image](https://github.com/user-attachments/assets/282f0812-1b8a-4e10-88b9-2d9e6a41da71)

**Comment by xcc3306** [comment]
这个是什么原因呢，有没有大佬，可以帮帮我（┬＿┬）

**Comment by Mintimate** [comment]
什么游戏？什么进程出现这个问题？ 而且这个属于客户端问题，去小狼毫那边提问或者鼠须管比较好。

**Comment by xcc3306** [comment]
> 什么游戏？什么进程出现这个问题？而且属于这个客户端问题，去小狼后面提问或者鼠须管比较好。

可是，我之前用雾凇拼音的时候没有出现这个问题呀，我有点搞不明白是那里方面的问题😮‍💨

**Comment by Mintimate** [comment]
重启小狼毫进程。这个不可能是薄荷配置弄的。要么小狼毫出现bug，或者小狼毫和游戏适配问题；要么自己覆写的配置出现问题。

**Comment by xcc3306** [comment]
> 重启小狼毫进程。这个不可能是薄荷配置弄的。要么小狼毫出现bug，或者小狼毫和游戏适配问题；要么自己覆写的配置出现问题。
好，那我重启一下试试，💪

**Comment by Mintimate** [comment]
也不用重启电脑，重启小狼毫进程就可以了。还是不行，检查`weasel.custom.yaml`的配置是否正确了

**Comment by xcc3306** [comment]
![image](https://github.com/user-attachments/assets/e0a32baa-4f14-4296-91f5-bf198ec7fd9d)
hai shi还是这样的，
我的weasel.custom.yaml，这个文件，我我其他的都注掉了，只留这两个，他还是这样
![image](https://github.com/user-attachments/assets/0ebd008f-5325-43c7-8e0d-358cd7b9e42b)

**Comment by xcc3306** [comment]
算了，我从头开始，从新配置一遍，再试试吧，◝(*⁰▿⁰*)◜
