### ISSUE TITLE
如何在通过iCloud软链接同步配置和字典的情况下同步词库

### ISSUE THREAD

**Issue by kennir** [Mintimate/oh-my-rime#118]
如何在通过iCloud软链接同步配置和字典的情况下同步词库

Macos按照文档的方法可以让整个Rime目录和苍输入法同步， 但是installation.yaml下的 installation_id 也会被同步成一个， 这时候如何sync MacBook和仓输入法的用户词库呢？ 

谢谢

**Comment by Mintimate** [comment]
按薄荷文档内同步用户词典方法就可以了，就是ln的软链接。

**Comment by kennir** [comment]
> 按薄荷文档内同步用户词典方法就可以了，就是ln的软链接。

谢谢作者飞快的回复

我测试下来好像不行， 我在鼠须管里打了一个 “都是” ， 但是iPhone上还是没有这个词组， 配置目录下的sync目录只有一个目录，我推测是不是icloud把 "installation.yaml" 这个文件给同步了，这样我自定义的installation_id都变成一个了，所以鼠须管和仓输入法导出的词库都在一个目录下，相互覆盖了

我现在的解决方案是不通过link的方式来同步整个薄荷的配置，而是只同步sync的词库，仓输入法下的配置还是手动复制过去一份

**Comment by Mintimate** [comment]
macOS的iCloud是后台会自动下载的，iOS的iCloud文件是要手动点击下载同步的。

**Comment by kennir** [comment]
感谢，我再测试下， 现在同步词库好像也不行， 鼠须管里打的词组仓输入法里不出来 😢
