### ISSUE TITLE
default.yaml里有几个切换状态的键位默认设置无效。

### ISSUE THREAD

**Issue by Hynpothalamus** [Mintimate/oh-my-rime#120]
![QQ_1722304091134](https://github.com/user-attachments/assets/d9a74e91-a481-4ec8-82ab-ead349ae4338)
图中框出的几个键位无法正常触发，查文档后将数字改为对应的符号的英文名后切换成功。
![QQ_1722304132768](https://github.com/user-attachments/assets/bd4b21de-b736-4f40-984c-092665e6e78d)

**Comment by Mintimate** [comment]
这个是librime源码内的，为适配rimetool，所以这里冗余一遍。薄荷文档内已经写了配置方法。

另外，不用群里反馈一次，又issue一次，二选一即可。
