### ISSUE TITLE
Windows下使用东风破安装异常

### ISSUE THREAD

**Issue by fevenor** [Mintimate/oh-my-rime#123]
Windows下使用小狼毫自带的东风破安装存在两个问题。使用的版本为 Weasel 0.16.1
## 文档中的安装命令错误

[教程](https://www.mintimate.cc/zh/guide/importMint.html#%E2%AD%90%E4%B8%9C%E9%A3%8E%E7%A0%B4%E5%AF%BC%E5%85%A5%E8%96%84%E8%8D%B7)提示输入的为
```
Mintimate/oh-my-rime:plum/full
```
实际应该为
```
Mintimate/oh-my-rime
```
否则下载路径将错误。

## 安装后存在文件缺失

安装后，在用户目录下，缺少`dicts`和`lua`两个文件夹及其文件，导致输入法无法正常使用。

**Comment by Mintimate** [comment]
不对。教程内的`Mintimate/oh-my-rime:plum/full`为plum的处方写法，参考plum文档：
- [Plum: 安装与更新输入方案](https://github.com/rime/weasel/wiki/%E5%AE%89%E8%A3%85%E4%B8%8E%E6%9B%B4%E6%96%B0%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88)

Windows如果不支持，那么就是Windows没有配置`git`，可以先输入`plum`，等待自动配置好后，输入`Mintimate/oh-my-rime:plum/full`即可更新：

![操作效果](https://github.com/user-attachments/assets/87b21437-9d01-4e96-9971-d7785b9abcde)

**Comment by fevenor** [comment]
> 不对。教程内的`Mintimate/oh-my-rime:plum/full`为plum的处方写法，参考plum文档：
> 
> * [Plum: 安装与更新输入方案](https://github.com/rime/weasel/wiki/%E5%AE%89%E8%A3%85%E4%B8%8E%E6%9B%B4%E6%96%B0%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88)
> 
> Windows如果不支持，那么就是Windows没有配置`git`，可以先输入`plum`，等待自动配置好后，输入`Mintimate/oh-my-rime:plum/full`即可更新：
> 
> ![操作效果](https://private-user-images.githubusercontent.com/43734212/356862274-87b21437-9d01-4e96-9971-d7785b9abcde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODkxMDksIm5iZiI6MTcyMzM4ODgwOSwicGF0aCI6Ii80MzczNDIxMi8zNTY4NjIyNzQtODdiMjE0MzctOWQwMS00ZTk2LTk5NzEtZDc3ODViOWFiY2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1MDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNDU5MDFjY2U0YmZlYmVjZDMwNjI4MWYzYjRhN2QzZGZjZjhjODZkMjIyOWFiMmFjNzI4YzUwNDVmOTkzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fVmKDhplWOX1LaX2T3N1I8g_AeGRNyiNbSJ_jY31ka8)

似乎是我这台的环境有问题，换了台开发用笔记本试了下，先执行`plum`，再执行`Mintimate/oh-my-rime:plum/full`，安装正常。

**Comment by Break-Unrestrained** [comment]
<img width="1175" height="565" alt="Image" src="https://github.com/user-attachments/assets/bd60ec59-1197-49f5-be9f-52a379dc0aa8" />
我的这个问题是什么？是因为没有安装在默认的安装路径的问题吗？如何是，该如何修改呢？

**Comment by HuberttFox** [comment]
输入法设定中的获取更多输入方案本质上是打开一个cmd窗口并执行rime-install.bat文件，而且已知在cmd运行会启动wsl的bash.exe（原因是wsl会将他的bash.exe放到了path较前的位置（cmd中运行bash.exe就会启动wsl））所以这里可以在rime-install.bat所在的文件夹下右键打开git-bash的快捷操作：“open git-bash here”，在git-bash内部运行rime-install.bat。
@Break-Unrestrained 

https://github.com/rime/plum/issues/84
https://github.com/rime/weasel/issues/1560#issuecomment-2942902376
