### ISSUE TITLE
删掉冗余配置

### ISSUE THREAD

**Issue by Hoysing** [Mintimate/oh-my-rime#127]
很多方案的配置文件都引入了default的快捷键配置，但是在方案配置中又复制了一遍default的快捷键配置，那些相同配置啥可以去除的。比如切换中英文，我可以直接default文件进行全局配置即可，而不会被那些方案的配置所覆盖，如果在特有方案改，那也可以覆盖来改，不过一般快捷键配置都是全局配置。

**Comment by Mintimate** [comment]
后续可以考虑删除 default 配置，每个方案模块内配置是为了适配 rimetool： https://github.com/yanhuacuo/rimetool

**Comment by Hoysing** [comment]
这是专门修正配置的项目吗？提供统一的格式以便他们修正？
