### ISSUE TITLE
使用 “/” + 首字母输入特殊符号功能异常

### ISSUE THREAD

**Issue by Rye42** [Mintimate/oh-my-rime#131]
版本: 24.08.31

问题描述: 
在输入“/fh”后会将“/f”的首个候选固定，而不显示符号选择界面，具体如图:
![image](https://github.com/user-attachments/assets/c221631e-8c5c-462b-b7bd-a4186957d923)![image](https://github.com/user-attachments/assets/f08b5844-44c9-4808-9fa3-3bed5bd41f09)

所有 "/" + 多字母的符号输入都不能正常使用，如"/sj"、“/lm”等等

**Comment by Mintimate** [comment]
正则捕捉问题，有时间我到时候修一下

**Comment by ref-y** [comment]
在你选用的输入方案中，把punct改为`punct: "^/([0-9]|10|[A-Za-z]+)$"`

> 版本: 24.08.31
> 
> 问题描述: 在输入“/fh”后会将“/f”的首个候选固定，而不显示符号选择界面，具体如图: ![image](https://private-user-images.githubusercontent.com/106509801/365575710-c221631e-8c5c-462b-b7bd-a4186957d923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTczOTAsIm5iZiI6MTcyNTk1NzA5MCwicGF0aCI6Ii8xMDY1MDk4MDEvMzY1NTc1NzEwLWMyMjE2MzFlLThjNWMtNDYyYi1iN2JkLWE0MTg2OTU3ZDkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwODMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWU5MjNkMGIzNjYxZDA0ZWYyY2IzNjFlZDdlNTUzN2ZmMzEwNzUyNWVkMTFlZTgxZGM3Y2ZjNTE5MTc5Mjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Piqeil4pJX9jqKDpJUKyb9upZOp3LEZHr-ViXLpiP5c)![image](https://private-user-images.githubusercontent.com/106509801/365575983-f08b5844-44c9-4808-9fa3-3bed5bd41f09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTczOTAsIm5iZiI6MTcyNTk1NzA5MCwicGF0aCI6Ii8xMDY1MDk4MDEvMzY1NTc1OTgzLWYwOGI1ODQ0LTQ0YzktNDgwOC05ZmEzLTNiZWQ1YmQ0MWYwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwODMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTQ5Y2IwODBiM2FlNDZlOGZjZjNjZGQ3ODE2NTkwZjI4OWUzM2U0YTM4YzAzN2Q5ZDdiMmU3MGVlNmE3N2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vTimaSkm8Vl3flV75YoIB-1PYJ0X_jFgQMaZ0bPiSGE)
> 
> 所有 "/" + 多字母的符号输入都不能正常使用，如"/sj"、“/lm”等等
