### ISSUE TITLE
配置很丰富，希望能增加一个五笔+白霜拼音的五笔拼音方案；

### ISSUE THREAD

**Issue by keepgoodfeeling** [Mintimate/oh-my-rime#133]
试用了下，很好用。
希望能增加一个五笔+白霜拼音的五笔拼音方案。

**Comment by Mintimate** [comment]
暂不考虑，五笔和拼音，本来就是两套没有关联的； 如果需要，可以自己使用`custom`文件去扩展`rime_mint.schema.yaml`的`abc_segmentor`实现单字情况下五笔输出。
