### ISSUE TITLE
怎么自造词

### ISSUE THREAD

**Issue by biange200** [Mintimate/oh-my-rime#134]
用的是五笔，怎么自己造词并记住

**Comment by YummyCocoa** [comment]
覆写`translator`内的`enable_user_dict`为true即可，参考: https://github.com/Mintimate/oh-my-rime/blob/a3c341342d76d12fc2ca8e49ddd9638b2ee69ca5/wubi86_jidian.schema.yaml#L135

不过形码本身字重低或没有，理论上不需要调频。

**Comment by biange200** [comment]
https://github.com/user-attachments/assets/967ad554-2638-4ba2-a579-beba7a9922c7

![Screenshot_20240916_111819.jpg](https://github.com/user-attachments/assets/8dca6c54-2033-4b7e-a1bb-dee2bfeb31b5)

启用后没用啊
