### ISSUE TITLE
Uw五笔反查貌似有问题

### ISSUE THREAD

**Issue by eko5624** [Mintimate/oh-my-rime#135]
Uw模式五笔反查只有在`薄荷配音-小鹤混输`和`小鹤双拼-薄荷定制`这2个方案里生效，在其它方案里不生效，是设计初衷吗？

**Comment by eko5624** [comment]
还发现个问题，反差出的某些字没有拼音标注。例如：`䟀` 这个字。

**Comment by YummyCocoa** [comment]
无法复现，在搜狗双拼、紫光双拼内，Uw反查正常使用。部分字不显示拼音，是因为限制反查使用的是基础拼音词典，用于加快查询速度。

**Comment by eko5624** [comment]
在`薄荷拼音-全拼输入`不能用Uw模式反查

**Comment by eko5624** [comment]
> 部分字不显示拼音，是因为限制反查使用的是基础拼音词典，用于加快查询速度。
用五笔反查就是因为不知道要反查的字的拼音。不知道拼音的字一般是不常见的字。所以对于Uw五笔反查，建议使用更全的单字拼音词典感觉更妥当。

**Comment by Mintimate** [comment]
`薄荷拼音-全拼输入`的反查确实有问题，这个到时候会修修

**Comment by Mintimate** [comment]
YAML格式内，用换行和对齐来区分对象。https://github.com/Mintimate/oh-my-rime/commit/46347cc23f851c2b696e690374006cbfd5c4c4c4 内的 124行多了一个回车，导致解析对象出现问题。
