### ISSUE TITLE
在Notion中使用“薄荷拼音-全拼输入”的配置时的问题

### ISSUE THREAD

**Issue by 7sasuke7l** [Mintimate/oh-my-rime#136]
Notion中的快捷键"Ctrl+Shift+E"是行内公式输入模式，但是如果此时的输入法是薄荷拼音-全拼输入的配置时，此快捷键无效，切换到其他配置即正常，我也不知道Ctrl+Shift+E是否和薄荷拼音的快捷键冲突，希望解决.

**Comment by Mintimate** [comment]
应该是和Emoji的快捷键冲突了，覆写快捷键 https://github.com/Mintimate/oh-my-rime/blob/46347cc23f851c2b696e690374006cbfd5c4c4c4/rime_mint.schema.yaml#L354 就可以了。
