### ISSUE TITLE
五笔拼音堆一起了，是否可以按目录模块化？

### ISSUE THREAD

**Issue by arkxfly** [Mintimate/oh-my-rime#137]
刚接触 rime 不久，有个疑问，是否可以按目录进行模块化呢，可以按需下载，像是五笔不会，基本永远用不上。

**Comment by Mintimate** [comment]
目前薄荷用户就有五笔用户，并且存在五笔和拼音反查； 如果剔除将影响反查功能的编译导致编译部署出现问题，所以薄荷主分支不会剔除。

如果要剔除五笔，那么可以自己fork本仓库，剔除五笔部分，自行维护。

虽然不会剔除五笔，但是短期内应该不会新增新的输入，除非和五笔一样，有作者授权~

**Comment by Mintimate** [comment]
不能，只能读根目录方案。 词典可以，方案不行
