### ISSUE TITLE
修改全局候选词数量不起作用

### ISSUE THREAD

**Issue by cphotor** [Mintimate/oh-my-rime#138]
无论是在default.yaml还是default.custom.yaml中修改都永远是默认的6个，需要修改输入法方案（例如小鹤双拼）才有效。可能因为在每个输入法方案中都写死了候选词数量，建议把方案配置中的page_size都去掉，只留下全局的，这样全局配置才能起作用。

**Comment by Mintimate** [comment]
Duplicate of https://github.com/Mintimate/oh-my-rime/issues/120 

即： 为了适配 [rimetool](https://gitee.com/wubi98/rimetool) ， 在方案内有重复书写一边 page_size 数据。 需要修改方案设置才会生效，比如：

https://github.com/Mintimate/oh-my-rime/blob/46347cc23f851c2b696e690374006cbfd5c4c4c4/rime_mint.schema.yaml#L389

建议使用 rime_mint.custom.yaml 文件覆写实现。
