### ISSUE TITLE
你好，英文单词输入，能否支持在英文模式下输入呢

### ISSUE THREAD

**Issue by xqhjay** [Mintimate/oh-my-rime#140]
就是在asiic mode 为英文模式时，输入英文不直接上屏，而是会作为输入码，对接英文单词翻译器呢？

**Comment by Mintimate** [comment]
rime 不支持自定义 asiic mode。实现不了。

**Comment by xqhjay** [comment]
> rime 不支持自定义 asiic mode。实现不了。

小狼毫和同文都支持 librime-lua 吧，可以实现的，参考:

https://github.com/shewer/rime-english

可以移植过来

**Comment by Mintimate** [comment]
不行，你发的还是中文模式输入。 asiic mode 也不载入 lua，不能实现。

**Comment by xqhjay** [comment]
> 不行，你发的还是中文模式输入。 asiic mode 也不载入 lua，不能实现。

这个我试过了，是可以的，可能还需要优化和改造

https://github.com/sdadonkey/rime-english
