### ISSUE TITLE
薄荷输入法无法正常打字的问题

### ISSUE THREAD

**Issue by QQ29039884** [Mintimate/oh-my-rime#144]
今天根据教程打包下载了薄荷输入法并且引入，相关输入法已经在输入法列表里面了
现在的问题就是选择任意款的薄荷输入法，输入后都只有英文（试过切换中/英仍然如此）
所以想了解一下大概哪里出了问题。
因为小狼毫自带的 简体输入是可以用的，所以排除输入法引擎的问题。

**Comment by Mintimate** [comment]
一般这种情况只有 rime 核心 librime 版本过低才会这样。如果是小狼毫 0.14.3 以及以前版本会这样。高版本的小狼毫通常不会有问题，可以尝试更新到测试版本: https://github.com/rime/weasel/releases/tag/latest

或者你可以试试看，在同步用户词典后(备份用户数据)： 退出小狼毫服务 - 删除 build - 重启小狼毫服务 - 重新部署。

**Comment by QQ29039884** [comment]
您分析的很有道理，正在努力的down您推荐你的最新版安装包（内陆下载仓库的速度不得不说实在是太感人），试过后再回来追评；
至于为什么我安装了比较旧的版本的原因……
好像是之前雾凇方案的教程推荐的rime版本，因为当时想配雾凇方案使用（当然配置失败咯）……
所以才过来转投薄荷阵营。
感谢及时回复，不得不说 rime 输入法总体来说比目前流行的输入法都好用很多，就是安装配置过程对于非码农（或者我这种伪码农）来说不太友好 emoji:cry 。

**Comment by Mintimate** [comment]
薄荷内部的各个方案有互相交集。如果是只想要其中一种输入凡是，需要手动在文件内移除依赖部分，尤其是 Lua 部分，你可以参考日志。
