### ISSUE TITLE
在Fcitx5框架下薄荷输入法皮肤不能使用

### ISSUE THREAD

**Issue by bingling60** [Mintimate/oh-my-rime#156]
我在安卓端的fcitx5和linux arm的fcitx5框架下均部署薄荷输入法，但薄荷输入法自带皮肤均不能使用，这个情况是和fcitx5有关吗？
我同时发现在windows中文韵框架下皮肤正常使用！
这是为什么？有大佬给个解答吗？

**Comment by Mintimate** [comment]
无法复现，Fcitx 5 的外观，Rime 配置是无法修改的，你是不是没下载薄荷配置的 Fcitx 5皮肤包并选中： https://www.mintimate.cc/zh/demo/diffAppearance.html#linux%E5%A4%96%E8%A7%82

**Comment by bingling60** [comment]
好的谢谢，明白了，感谢您的回答
