### ISSUE TITLE
自然码的双拼模糊音一直不起作用

### ISSUE THREAD

**Issue by CocoaTakasaki** [Mintimate/oh-my-rime#160]
如图所示，已用custom覆写，但始终没能打出模糊音
![image](https://github.com/user-attachments/assets/01e29f6d-13b1-43b2-8a43-d343ed24aa0b)
开头如下，这个custom文件应当是被调用的，因为当我删掉里面的内容后无法打字了
![image](https://github.com/user-attachments/assets/08dfb7a6-00b9-430c-8bd7-c121f5d68cc3)

**Comment by Mintimate** [comment]
第二行 YAML 格式就开始错了。缩进没统一。

**Comment by CocoaTakasaki** [comment]
这一段我是从原yaml抄下来的
![image](https://github.com/user-attachments/assets/12848abd-bf8e-4e7f-98ae-131a77b93262)
在我修改之后，输入法变得难以打字了
![image](https://github.com/user-attachments/assets/731908ef-a999-42bc-855a-916590a3a66b)

**Comment by Mintimate** [comment]
你抄过去也要注意上级格式呀，你已经有一个一级节点 patch 了，那么后续也需要保持 YAML 格式层级。换个好点的文本编辑器，后面添加的内容批量缩进吧。另外，不建议双拼用模糊拼音，重码率又上来了。
