### ISSUE TITLE
各输入法中的page_size设置覆盖默认设置

### ISSUE THREAD

**Issue by emptylight370** [Mintimate/oh-my-rime#169]
在小狼毫中使用时发现输入法配置中的menu/page_size会覆盖默认配置中的page_size，使用custom文件覆盖输入法设置也不行，只能删除输入法中的page_size才能使用默认设置中覆盖的page_size。

**Comment by Mintimate** [comment]
使用输入法的 custom 可以覆盖； Duplicate with https://github.com/Mintimate/oh-my-rime/issues/120
