### ISSUE TITLE
中文状态下，大写字母锁定开启，输入英文后无法空格键上屏，也无法退格键删除

### ISSUE THREAD

**Issue by tiantangzhixia** [Mintimate/oh-my-rime#170]
中文状态下，大写字母锁定开启，输入英文后无法空格键上屏，也无法退格键删除，只能关闭大写字母锁定后才能操作。
请问这个问题是需要更改配置文件吗？还是rime输入法本身的问题？

**Comment by Mintimate** [comment]
试了一下，macOS 上的鼠须管无法复现

**Comment by tiantangzhixia** [comment]
用的小狼毫0.16.3.0版本，配置了薄荷拼音，可以轻易复现。

**Comment by Mintimate** [comment]
群友也没复现，不过不排除电脑问题。还是有问题，就把大写的映射关闭吧。这部分是用来 Shift 映射的。

![92724aa722100621b726220c4e971897](https://github.com/user-attachments/assets/68242d42-d3cf-491a-b6cc-393d0c896aea)

**Comment by weijn0214** [comment]
我的也是这样，大写后无法删除， 小狼毫+ 霧凇拼音   、小狼毫都是这样
