### ISSUE TITLE
五笔拼音输入

### ISSUE THREAD

**Issue by JuneOx** [Mintimate/oh-my-rime#20]
能否支持五笔拼音混合输入

**Comment by Mintimate** [comment]
拼音和五笔本质上交际很少，而且五笔我其实不会⊙.⊙。

目前也没有人提供有关五笔的pr，五笔维护会很难。

而且五笔和拼音词库组合有点奇怪，尤其是词的优先级不知道如何判断。

综合上述原因，暂时不考虑五笔和拼音混输。
