### ISSUE TITLE
无法使用delimiter「'」

### ISSUE THREAD

**Issue by Stumble** [Mintimate/oh-my-rime#22]
## Expected behavior:
```
xi'an => 西安
```

## What happened:

看起来似乎是因为`'`被绑定成了`「`，无法使用`'`来分割xian，而是会终止输入并且输入一个`「`

```
西「安
```

**Comment by Mintimate** [comment]
嗷，这个问题看了一下…… 我也以为是symbol冲突了，但是后来发现，是我在`speller`内，没有设置`delimiter`的原因😅。

下一次comment我将会补全。不过我在想应该是用`` ` ``作为手动分割，还是`'`作为好？ 暂时先用`` ` ``吧😁

**Comment by Stumble** [comment]
感谢！

**Comment by Mintimate** [comment]
> 这个问题后来解决了么？一直都使用'作为分隔符，现在要换一个，还挺麻烦的

如果你看了这个 issue 具体内容和代码注释，你就不会问这个。自己自定义就好

**Comment by zfdang** [comment]
看到了，修改了delimiter了
