### ISSUE TITLE
Proposal to change the license of the Mintimate/oh-my-rime from GPL-2.0 to GPL-3.0

### ISSUE THREAD

**Issue by OrLojqrG** [Mintimate/oh-my-rime#27]
Presently, the license of the Mintimate/oh-my-rime is GPL-2.0. However, the project incorporates vocabulary content from the iDvel/rime-ice, which is licensed under GPL-3.0. This discrepancy in licenses could potentially lead to legal complications. Therefore, it is proposed to modify the license of the oh-my-rime project from GPL-2.0 to GPL-3.0 to comply with the requirements of the iDvel/rime-ice's license.

**Comment by Mintimate** [comment]
Oops, I really didn’t pay attention to the GPL agreement version of the ice-rime when I created the project; fortunately, GPL3.0 and GPL2.0 will not have any impact on the project. I will change the agreement to GPL3.0 later.
