### ISSUE TITLE
无法连续输入。。。。

### ISSUE THREAD

**Issue by oay-nj** [Mintimate/oh-my-rime#31]
![image](https://github.com/Mintimate/oh-my-rime/assets/126548717/4eedaf1e-afef-4d84-b68a-37db4cca05b2)

**Comment by oay-nj** [comment]
好了，可以开心的打。。。。。。。了

**Comment by limboinf** [comment]
好几个配置文件存在 punctuator 配置，我分别配置 double_pinyin_flypy.schema.yaml rime_mint.schema.yaml 和 symbols.yaml 将 ["。"] 改成 "。" 才OK的 。。。。

**Comment by YummyCocoa** [comment]
> 好几个配置文件存在 punctuator 配置，我分别配置 double_pinyin_flypy.schema.yaml rime_mint.schema.yaml 和 symbols.yaml 将 ["。"] 改成 "。" 才OK的 。。。。

这个问题，还是为了打网址时候而设计的。比如，`tool.mintimate.cn`，这样不用切换到 ABC 即可在浏览器上输入。 不过`symbols.yaml`也被我们改多，确实容易让使用者造成困扰。之后会把`symbols.yaml`内的移除。或者看看有没有更好的解决方法。
