### ISSUE TITLE
怎么反查没效果，我从GitHub上下载下来大

### ISSUE THREAD

**Issue by 986138497** [Mintimate/oh-my-rime#33]
比如我想打三个牛牛牛，这个读音

**Comment by YummyCocoa** [comment]
怎么输入的？ 操作系统是什么？ 用的是那个版本的Rime客户端？

**Comment by 986138497** [comment]
> 怎么输入的？ 操作系统是什么？ 用的是那个版本的Rime客户端？

<img width="550" alt="image" src="https://github.com/Mintimate/oh-my-rime/assets/18497058/9ca6b8b9-2ce6-4f55-a67d-55e88dffdb7e">
操作系统是14.3.1，就是输入uu后面跟niuniuniu， 后面不联想拼音，都是拼音

**Comment by 986138497** [comment]
> 怎么输入的？ 操作系统是什么？ 用的是那个版本的Rime客户端？

最新版0.16.2版本

**Comment by YummyCocoa** [comment]
没有遇到过了；之前的0.16.2鼠须管ACTION版本是没有Lua模块，不过反查不需要Lua模块；而且看起来你这个不是ACTION版本的。你可以删除鼠须管build文件夹内的文件，重启系统后重新部署试试看。

**Comment by 986138497** [comment]
> 没有遇到过了；之前的0.16.2鼠须管ACTION版本是没有Lua模块，不过反查不需要Lua模块；而且看起来你这个不是ACTION版本的。你可以删除鼠须管build文件夹内的文件，重启系统后重新部署试试看。

我删除下面的了，还是不行， 都是拼音
