### ISSUE TITLE
薄荷拼音-全拼输入无法切换简繁

### ISSUE THREAD

**Issue by marcushsu** [Mintimate/oh-my-rime#37]
在没显示候选字菜单时按了切换键，会出现“漢字”提示，但是打出来的候选字仍然都是简体字，上的也是简体字。
在有显示候选字菜单时按了切换键则毫无作用，都是简体字。

换回朙月拼音又正常。用的是Windows版小狼毫。

**Comment by YummyCocoa** [comment]
「Ctrl + ~」手动激活呢？ 试试看输入「启示录」有没有变成「啓示錄」

**Comment by marcushsu** [comment]
> 「Ctrl + ~」手动激活呢？ 试试看输入「启示录」有没有变成「啓示錄」

我就是这样激活的，再试一次情况一样的咯，「启示录」还是「启示录」。

**Comment by marcushsu** [comment]
> Weasel的具体版本是多少？0.14.3 还是 0.15.0 + 或者 Action 每夜版本？ Windows是Windows 7 以及以下，还是高于Windows 7？

再試一次，Ctrl + ~的方案選單可選，結果有效，但是快捷鍵仍然無效。而快捷鍵在朙月拼音是有效的。
0.14.3、0.15.0 跟  Night Build (2 weeks ago) 都試過了，情況一樣。Windows 版本 10 Pro 22H2。

**Comment by Mintimate** [comment]
那寄了，我这里已经无法解决了。等别的小伙伴看看能不能解决了

**Comment by mirtlecn** [comment]
https://github.com/Mintimate/oh-my-rime/blob/e6f76b1bbc23f29b512867085fb21ea096820244/rime_mint.schema.yaml#L28

这一行吗，因为写错了。Weasel 获取的是被 Shift 键转换后的 keycode

```
Control+Shift+exclam
```

**Comment by Mintimate** [comment]
> 我是说，方案里面应该写两个 binding，含有 Shift 键 + 数字的应该这么写：
> 
> ```yaml
> - {accept: "Control+Shift+exclam", toggle: transcription, when: has_menu} 
> - {accept: "Control+Shift+1", toggle: transcription, when: has_menu}
> ```

我觉得，他应该是无法启动OpenCC，无论是binding快捷键还是「Ctrl + ~」内手动激活。 不清楚为什么了

**Comment by mirtlecn** [comment]
> 我是说，方案里面应该写两个 binding，含有 Shift 键 + 数字的应该这么写：
> 
> ```yaml
> - {accept: "Control+Shift+exclam", toggle: transcription, when: has_menu} 
> - {accept: "Control+Shift+1", toggle: transcription, when: has_menu}
> ```

@marcushsu 像我这么改，再按 Control + Shift + 1 看看行不行。

**Comment by Mintimate** [comment]
> > 我是说，方案里面应该写两个 binding，含有 Shift 键 + 数字的应该这么写：
> > ```yaml
> > - {accept: "Control+Shift+exclam", toggle: transcription, when: has_menu} 
> > - {accept: "Control+Shift+1", toggle: transcription, when: has_menu}
> > ```
> 
> @marcushsu 像我这么改，再按 Control + Shift + 1 看看行不行。

我测试了了，确实是我写错了…… 我下次push的时候改一下。 感谢🌹

**Comment by marcushsu** [comment]
这样可以了，感谢两位。但是有点不太明白，朙月拼音是建议改toggle: simplification的：
`{accept: "Control+Shift+4", toggle: simplification, when: always} `

**Comment by Mintimate** [comment]
simplification 是明月拼音的OpenCC的繁体转换，你可以看它其他的配置有实现这个tag。 薄荷内，是定义transcription这个tag并实现。
