### ISSUE TITLE
能否添加手机端支持。

### ISSUE THREAD

**Issue by onlyistranger** [Mintimate/oh-my-rime#38]
目前分享的方案直接复制到手机端（安卓）均有各种问题，尚不能傻瓜式一键部署使用。

**Comment by Mintimate** [comment]
小企鹅 Fcitx5 Android可以即开即用。

**Comment by KyoSakuyo** [comment]
> 小企鹅 Fcitx5 Android可以即开即用。

因为小企鹅的默认用户词库存储在/Android/data/...文件夹，且无法更改。如果没有root权限，同步起来非常不方便。

如果能适配同文，用户自定义词典的双端同步会方便许多。

**Comment by Mintimate** [comment]
> > 小企鹅 Fcitx5 Android可以即开即用。
> 
> 因为小企鹅的默认用户词库存储在/Android/data/...文件夹，且无法更改。因此，在较新的安卓设备中，如果没有root权限，同步起来非常不方便。（包括FolderSync在内，很多同步App都难以访问应用数据。）
> 
> 如果能适配同文，用户自定义词典的双端同步会方便许多。

尝试了一下，目前如果用同文。需要把`default.custom.yaml`修改为`default.yaml`；这样部署就没问题了。 不过让我比较头痛的是配置的主题。估计没那么快了，需要等待PR了。

**Comment by onlyistranger** [comment]
> > > 小企鹅 Fcitx5 Android可以即开即用。
> > 
> > 
> > 因为小企鹅的默认用户词库存储在/Android/data/...文件夹，且无法更改。因此，在较新的安卓设备中，如果没有root权限，同步起来非常不方便。（包括FolderSync在内，很多同步App都难以访问应用数据。）
> > 如果能适配同文，用户自定义词典的双端同步会方便许多。
> 
> 尝试了一下，目前如果用同文。需要把`default.custom.yaml`修改为`default.yaml`；这样部署就没问题了。 不过让我比较头痛的是配置的主题。估计没那么快了，需要等待PR了。

手机端部署后不能输入中文。尝试切换了几种输入模式依然只有英文，暂时放弃了。

**Comment by Mintimate** [comment]
> > > > 小企鹅 Fcitx5 Android可以即开即用。
> 
> > > 
> 
> > > 
> 
> > > 因为小企鹅的默认用户词库存储在/Android/data/...文件夹，且无法更改。因此，在较新的安卓设备中，如果没有root权限，同步起来非常不方便。（包括FolderSync在内，很多同步App都难以访问应用数据。）
> 
> > > 如果能适配同文，用户自定义词典的双端同步会方便许多。
> 
> > 
> 
> > 尝试了一下，目前如果用同文。需要把`default.custom.yaml`修改为`default.yaml`；这样部署就没问题了。 不过让我比较头痛的是配置的主题。估计没那么快了，需要等待PR了。
> 
> 
> 
> 手机端部署后不能输入中文。尝试切换了几种输入模式依然只有英文，暂时放弃了。

你是不是直接把`default.custom.yaml`重命名为`default.yaml`的呢？ 这样是不行的，custom是patch的格式。没事，之后我完善一下，到时候感兴趣可以再玩玩。

**Comment by onlyistranger** [comment]
> > > > > 小企鹅 Fcitx5 Android可以即开即用。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 因为小企鹅的默认用户词库存储在/Android/data/...文件夹，且无法更改。因此，在较新的安卓设备中，如果没有root权限，同步起来非常不方便。（包括FolderSync在内，很多同步App都难以访问应用数据。）
> > 
> > 
> > > > 如果能适配同文，用户自定义词典的双端同步会方便许多。
> > 
> > 
> > > 
> > 
> > 
> > > 尝试了一下，目前如果用同文。需要把`default.custom.yaml`修改为`default.yaml`；这样部署就没问题了。 不过让我比较头痛的是配置的主题。估计没那么快了，需要等待PR了。
> > 
> > 
> > 手机端部署后不能输入中文。尝试切换了几种输入模式依然只有英文，暂时放弃了。
> 
> 你是不是直接把`default.custom.yaml`重命名为`default.yaml`的呢？ 这样是不行的，custom是patch的格式。没事，之后我完善一下，到时候感兴趣可以再玩玩。

我直接重命名的🤣 那坐等更新了再试试
