### ISSUE TITLE
为什么视频中配置完成后，输入法候选词界面是水平横向的，但是我配置完是垂直纵向的？

### ISSUE THREAD

**Issue by ghost** [Mintimate/oh-my-rime#39]
windows10 系统，配置完后，重新部署了好几次，还注销过

![image](https://github.com/Mintimate/oh-my-rime/assets/48472903/3e95f35a-77ab-4e46-9ca4-0248eef9e4d1)

![image](https://github.com/Mintimate/oh-my-rime/assets/48472903/ef917874-d5ee-4750-8240-df0aee99811b)

**Comment by YummyCocoa** [comment]
反馈群内，改为垂直的呼吁比较高。 就改垂直了。 需要改回去的话。…… 

小狼毫的配置文件内水平参数调整为 true ：[https://github.com/Mintimate/oh-my-rime/blob/e6f76b1bbc23f29b512867085fb21ea096820244/weasel.yaml#L47](https://github.com/Mintimate/oh-my-rime/blob/e6f76b1bbc23f29b512867085fb21ea096820244/weasel.yaml#L47)

**Comment by Corgile** [comment]
Debian12中不论修改哪个文件，都是vertical的， 并且改了字号并没有任何变化
![image](https://github.com/Mintimate/oh-my-rime/assets/48396880/6d69dbe2-2755-41ed-aada-e49cd41ec0e6)

![image](https://github.com/Mintimate/oh-my-rime/assets/48396880/a80bf23b-8b0f-4126-836f-59c4ee7ad239)

**Comment by Mintimate** [comment]
Linux受限于系统，配置取决于输入法框架配置，比如iBus和Fcitx5的配置

**Comment by Corgile** [comment]
> Linux受限于系统，配置取决于输入法框架配置，比如iBus和Fcitx5的配置

用的是ibus

**Comment by Mintimate** [comment]
> > Linux受限于系统，配置取决于输入法框架配置，比如iBus和Fcitx5的配置
> 
> 用的是ibus

参考这个： [https://github.com/rime/ibus-rime/issues/42](https://github.com/rime/ibus-rime/issues/42)
