### ISSUE TITLE
使用人民币大写时如何选择候选项？

### ISSUE THREAD

**Issue by yaoliyc** [Mintimate/oh-my-rime#41]
![Snipaste_2024-03-15_15-49-15](https://github.com/Mintimate/oh-my-rime/assets/5663509/ab705f47-80f5-47c4-8fe2-bf8d32b06070)
当使用人民币大写时该如何选择候选项？默认的数字会被当成输入的一部分而不是预期选中第几个。

**Comment by Mintimate** [comment]
目前是数字键参与大小写输入，小键盘用来选候选词。 不过没有小键盘的话，我一般是方向键移动后空格，或者直接简单粗暴，用鼠标🖱。

**Comment by yaoliyc** [comment]
> 目前是数字键参与大小写输入，小键盘用来选候选词。 不过没有小键盘的话，我一般是方向键移动后空格，或者直接简单粗暴，用鼠标🖱。

又试了下，上下方向键可以。数字小键盘只有2是在候选项起作用，鼠标点击被当成输入内容处理了。

**Comment by Mintimate** [comment]
没错，我测试了一下。 目前是上下方向键和空格了。使用鼠标无法操作😅。

**Comment by answork02** [comment]
> 目前是数字键参与大小写输入，小键盘用来选候选词。 不过没有小键盘的话，我一般是方向键移动后空格，或者直接简单粗暴，用鼠标🖱。

是否能实现反向呢，即小键盘输入，大键盘选字？

**Comment by Mintimate** [comment]
补充一下，现在这个问题，群友有分享，是可以通过 Ctrl + 数字 进行候选的。比如： Ctrl + 2 选人民币大写时候的第二候选项。
