### ISSUE TITLE
无法删除自造词

### ISSUE THREAD

**Issue by dboyplus** [Mintimate/oh-my-rime#45]
MacOS 14.4，MacBook pro
无法删除自造词，按照wiki和其他搜到的文档，尝试过Fn + Shift + BackSpace，ctrl + K，Ctrl + D，Command + K等等各种组合，都无法删除自造词。
同时也确定这个自造词是之前错误上屏的，并非系统词典自带的。

不知道没有大佬可以指点下，谢谢！

**Comment by Mintimate** [comment]
鼠须管使用 `Fn + ⇧ + ⌫`
小狼毫使用 `Ctrl/Shift + Del`

效果是这样的：
![i删除自造字](https://github.com/Mintimate/oh-my-rime/assets/43734212/6a32375f-db80-4e11-b209-882eb1164dc8)
