### ISSUE TITLE
大家打字快时，候选是否卡顿？

### ISSUE THREAD

**Issue by molezz** [Mintimate/oh-my-rime#46]
Windows11下，打字快，候选字界面比较卡顿，是不是因为默认字库比较大？
切了几个主题都是这样，可能就是字库了？

**Comment by Mintimate** [comment]
目前Weasel会存在卡顿问题，Squirrel等平台不会，如果出现卡顿，可以移除雾凇词库内的扩展部分，也就是ext的词库。
