### ISSUE TITLE
请问如何彻底全局关闭emoji

### ISSUE THREAD

**Issue by kanoto** [Mintimate/oh-my-rime#47]
即使用 control+` 配置中关掉emoji, 切换窗口焦点后, emoji又回来了.

rime_mint.schema.yaml中的

    switches:
      - name: emoji_suggestion
        reset: 0
        states: [ "😣️","😁️"]

reset设为0也不行. 请问有什么办法么?

**Comment by Mintimate** [comment]
删除输入分案内`filters`内的`simplifier@emoji_suggestion`以及相关属性即可。

**Comment by kanoto** [comment]
> 删除输入分案内`filters`内的`simplifier@emoji_suggestion`以及相关属性即可。

谢谢, 可以了!
