### ISSUE TITLE
小鹤混输不能反查

### ISSUE THREAD

**Issue by roverway** [Mintimate/oh-my-rime#49]
win11，用最新版薄荷拼音，以及rime 0.15（fxliang的最新版本），输入~u后不能启动反查，`~`直接上屏了，但是薄荷全拼的uu可以使用反查。
大佬能否看看为什么？

**Comment by YummyCocoa** [comment]
混熟目前是`uuu`反查，不是很好，还是会和正常输入冲突，后续可能还会调整，文档就没写。 可以看看这里先：
https://github.com/Mintimate/oh-my-rime/blob/1b59790b902e2e0d2758b1c89baf2637b8dc283b/rime_mint_flypy.schema.yaml#L358

**Comment by roverway** [comment]
> 混熟目前是`uuu`反查，不是很好，还是会和正常输入冲突，后续可能还会调整，文档就没写。 可以看看这里先：
> 
> https://github.com/Mintimate/oh-my-rime/blob/1b59790b902e2e0d2758b1c89baf2637b8dc283b/rime_mint_flypy.schema.yaml#L358

感谢大佬，我明白了。

**Comment by roverway** [comment]
大佬，刚发现新情况，反查后虽然能出现汉字，但是不出现该汉字的拼音了。比如`犇`，就是这样：
![图片](https://github.com/Mintimate/oh-my-rime/assets/657850/2f27cff4-d44e-460b-94c4-d4be3ccea79a)

**Comment by Mintimate** [comment]
> 大佬，刚发现新情况，反查后虽然能出现汉字，但是不出现该汉字的拼音了。比如`犇`，就是这样：
> 
> ![图片](https://github.com/Mintimate/oh-my-rime/assets/657850/2f27cff4-d44e-460b-94c4-d4be3ccea79a)
> 
> 

移除：
https://github.com/Mintimate/oh-my-rime/blob/1b59790b902e2e0d2758b1c89baf2637b8dc283b/rime_mint_flypy.schema.yaml#L320

另外，注音问题参考： #36

**Comment by roverway** [comment]
> > 大佬，刚发现新情况，反查后虽然能出现汉字，但是不出现该汉字的拼音了。比如`犇`，就是这样：
> > ![图片](https://private-user-images.githubusercontent.com/657850/314294390-2f27cff4-d44e-460b-94c4-d4be3ccea79a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTc4ODQsIm5iZiI6MTcxMDg5NzU4NCwicGF0aCI6Ii82NTc4NTAvMzE0Mjk0MzkwLTJmMjdjZmY0LWQ0NGUtNDYwYi05NGM0LWQ0YmUzY2NlYTc5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwMTE5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmVjYmYzMjdiZWQ3MDI2NjczMDUxYzUwMjQyOTQwMzNiZDczMDBmYzE3YmQzMWVkMmMwYjE3YTU4NWZhNDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RXy69YryI2XQty_AlNwezhiOojBAugfuiVCVBcrNSq0)
> 
> 移除：
> 
> https://github.com/Mintimate/oh-my-rime/blob/1b59790b902e2e0d2758b1c89baf2637b8dc283b/rime_mint_flypy.schema.yaml#L320
> 
> 另外，注音问题参考： #36

感谢，可以了。
rime的配置实在是复杂😅

**Comment by roverway** [comment]
请问大佬，我想练习小鹤音形，不知道薄荷定制能否设置成默认激活形码，不需要按; ?

**Comment by Mintimate** [comment]
> 请问大佬，我想练习小鹤音形，不知道薄荷定制能否设置成默认激活形码，不需要按`;` ?

小鹤官方就是自动四码上屏的音形，用那个就可以了。

**Comment by tyf2018** [comment]
> > 请问大佬，我想练习小鹤音形，不知道薄荷定制能否设置成默认激活形码，不需要按`;` ?
> 
> 小鹤官方就是自动四码上屏的音形，用那个就可以了。

自动四码上屏的音形，这个配置文件，官方网盘现在只有macos端的了。如果有Windows端的，方便分享一下么？

**Comment by Mintimate** [comment]
> > > 请问大佬，我想练习小鹤音形，不知道薄荷定制能否设置成默认激活形码，不需要按`;` ?
> 
> > 
> 
> > 小鹤官方就是自动四码上屏的音形，用那个就可以了。
> 
> 
> 
> 自动四码上屏的音形，这个配置文件，官方网盘现在只有macos端的了。如果有Windows端的，方便分享一下么？

rime 都是通用的，你把Windows的才开，里面的rime配置丢到macOS的鼠须管部署就可以了

**Comment by tyf2018** [comment]
@Mintimate 有一个新问题，Rime通过这种方式挂接小鹤音形，只能打出很少的字词，请问小鹤音形和其它双拼方案，词库是否不支持共用呢？如果不支持，有办法修正吗？

**Comment by Mintimate** [comment]
> @Mintimate 有一个新问题，Rime通过这种方式挂接小鹤音形，只能打出很少的字词，请问小鹤音形和其它双拼方案，词库是否不支持共用呢？如果不支持，有办法修正吗？

小鹤形的字就那一些字，具体看官方自己怎么维护，或者你自己扩充。音形本来就是四字上屏，你想和普通拼音混合，那么字符怎么判定插那个？ 这个看用户自己，薄荷目前不考虑这一方面。 另外，这个已经不是这个issue相关的了，不要让提这个issue的人频繁收到无关内容比较好
