### ISSUE TITLE
网站 Demo 英文页面图片错误

### ISSUE THREAD

**Issue by BlissfulAlloy79** [Mintimate/oh-my-rime#51]
出现问题的页面：
https://www.mintimate.cc/en/demo/

英文页面效果：
![image](https://github.com/Mintimate/oh-my-rime/assets/45236703/b43a1526-9d78-4432-b05b-68e08395a4f1)

对应的中文页面效果：
![image](https://github.com/Mintimate/oh-my-rime/assets/45236703/e172f47e-99c9-4776-82d9-e36ca4905c22)

一个小小的显示 bug

~~虽然应该不会有人看英文的文档吧~~

可能是我浏览器默认英文的原因？我是从 https://t.me/NewlearnerChannel 过来的，打开链接就默认是以英文显示

然后就发现了这个问题

**Comment by Mintimate** [comment]
嗷，下次我修一下，最近上班有点没什么时间。ಠ_ಠ
