### ISSUE TITLE
Fcitx5 for Android中，符号无法作为小鹤的trigger_word

### ISSUE THREAD

**Issue by zhufengning** [Mintimate/oh-my-rime#53]
除.以外的符号会直接上屏（可能是因为需要打开符号面板）。而设置为.则没有效果（如下图）。
设置为字母则没有问题。
![Screenshot_20240326-140314_MT管理器](https://github.com/Mintimate/oh-my-rime/assets/22849152/51d417e7-5646-4fbc-97cc-0da4bd335ea4)

**Comment by mirtlecn** [comment]
所有在 lua 正则中有特殊含义的符号都不能用。可以认为是那个辅码 lua 的 bug，也可以说本身点号做辅码引导符不太适合。

要提前做一遍转换 @HowcanoeWang

```lua
local function alt_lua_punc( s )
    return s:gsub( '([%.%+%-%*%?%[%]%^%$%(%)%%])', '%%%1' )
end
```

**Comment by HowcanoeWang** [comment]
先确认一下是不是因为遵照之前的有问题的readme，配置写错了

https://github.com/HowcanoeWang/rime-lua-aux-code/issues/15

**Comment by Mintimate** [comment]
> 先确认一下是不是因为遵照之前的有问题的readme，配置写错了
> 
> [HowcanoeWang/rime-lua-aux-code#15](https://github.com/HowcanoeWang/rime-lua-aux-code/issues/15)
> 
> PS：安卓方案是其他大佬贡献的，我本人其实也没有在自己的设备上调试成功

不是，我觉得是我把配置内容从`key_binder`里提取到外面的原因(也就是使用`axu_code/trigger_word`和`axu_code/show_aux_notice`控制）。感觉@mirtlecn 大佬的方法是对的。就是不知道具体怎么处理比较好……

**Comment by mirtlecn** [comment]
我受你脚本的启发，写过一个类似的辅码 lua。 @HowcanoeWang 

问题在正则里面，要处理一下辅码才能匹配：

https://github.com/mirtlecn/rime-radical-pinyin/blob/1071f1d41ee2014525a6ffa749ae1e23eabb7874/lua/search.lua#L58-L59

https://github.com/mirtlecn/rime-radical-pinyin/blob/1071f1d41ee2014525a6ffa749ae1e23eabb7874/lua/search.lua#L93-L98

**Comment by mirtlecn** [comment]
https://github.com/Mintimate/oh-my-rime/blob/afd7d6c9251e4425f15ee8176420b45e874c9fb1/lua/auxCode_filter.lua#L36-L37

这里，如果辅码引导符号是 lua 正则里面的特殊符号，比如本 issue 提到的 . 号，还有 % 等，用 .. 连接后要额外加 % 才能表示其原意。

**Comment by HowcanoeWang** [comment]
好吧，手机端的符号输入确实很麻烦，我之前的插件本来是钉死用`;`符号的，PC端不存在这个转译问题

**Comment by Mintimate** [comment]
> https://github.com/Mintimate/oh-my-rime/blob/afd7d6c9251e4425f15ee8176420b45e874c9fb1/lua/auxCode_filter.lua#L36-L37
> 
> 这里，如果辅码引导符号是 lua 正则里面的特殊符号，比如本 issue 提到的 . 号，还有 % 等，用 .. 连接后要额外加 % 才能表示其原意。

还给是大佬呀，又帮忙解惑了一次。这下我知道了，换成我这个配置，只需要：
```lua
    -- 設定預設觸發鍵為分號，並從配置中讀取自訂的觸發鍵
    env.trigger_key = config:get_string("axu_code/trigger_word") or ";"
    -- 添加 
    env.trigger_key = alt_lua_punc( env.trigger_key )
```
就可以了。 我测试了一下，果然可以了。
