### ISSUE TITLE
能否增加对颜文字的支持

### ISSUE THREAD

**Issue by jokerping** [Mintimate/oh-my-rime#54]
希望输入时可以显示对应的颜文字就像 emoji一样，实际上颜文字使用频率要比 emoji 更频繁。再就是如果能增加自定义表情包功能就更棒了

**Comment by Mintimate** [comment]
目前的颜文字是有的，你可以按`vv`查询颜文字词库。 之前有想过OpenCC实现，但是效果不是很好，甚至会影响输入，就使用这种方法。后续可能会考虑其他先导词，`vv`在小鹤内容易冲突。

**Comment by jokerping** [comment]
小鹤好像不支持vv啊，应该怎么按呢，另外[介绍页面反查部分](https://www.mintimate.cc/zh/demo/reverseWords.html#:~:text=%E3%80%81uw%E7%AD%89%EF%BC%9B-,%E5%8F%8C%E6%8B%BC%E5%86%85%E4%BD%BF%E7%94%A8~u,-%E3%80%81~w%E7%AD%89)，有个错误，双拼的反查我尝试默认是~~不是~u

**Comment by Mintimate** [comment]
小鹤支持，多翻几页后即可，这也是为什么在考虑换先导词的原因。 反查问题：
*  #49
