### ISSUE TITLE
【Feature Request】为移动端的全拼布局提供自动纠错

### ISSUE THREAD

**Issue by KyoSakuyo** [Mintimate/oh-my-rime#55]
小企鹅输入法的[fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons)输入方案最近刚刚实现了correction layout，这是[相关实现的commit](https://github.com/fcitx/fcitx5-chinese-addons/commit/c33e8b4d544e10232161e481a1f1e343d792eb69)。

目前小企鹅输入法的RIME插件暂时未内置自动纠错功能，插件维护者也暂时未准备给rime加入插件内置的纠错，并且[表示希望由方案提供者内置](https://t.me/fcitx5_android_group/134044)。

**Comment by Mintimate** [comment]
看了一下，感觉`rime只能自行配置`的意思，就是rime的`algebra`拼写转换。 可以参考全拼方案`algebra`内的**自动纠错**部分：
https://github.com/Mintimate/oh-my-rime/blob/e3f0a91d630dad34256609900824e51a320c0c48/rime_mint.schema.yaml#L195

**Comment by KyoSakuyo** [comment]
那对于基于QWERTY键盘物理位置上相近的按键按错的纠错，比如说把 ziangyao 和 ciangyao 纠正为xiangyao(想要)──这种纠也可以通过相关的方式实现吗？

**Comment by Mintimate** [comment]
参考刚刚的下一行：

https://github.com/Mintimate/oh-my-rime/blob/e3f0a91d630dad34256609900824e51a320c0c48/rime_mint.schema.yaml#L196

那么，你想要 ziang -> xiang、ciang -> xiang，这样即可：
```yaml
- derive/([zc])iang/$1iang/
```

**Comment by KyoSakuyo** [comment]
咦？我刚刚好像看到rime是自带了基于QWERTY物理位置的相关纠错的。

https://github.com/rime/librime/pull/228

只不过不知道在哪儿打开？

**Comment by Mintimate** [comment]
> 咦？我刚刚好像看到rime是自带了基于QWERTY物理位置的相关纠错的。
> 
> [rime/librime#228](https://github.com/rime/librime/pull/228)
> 
> 只不过不知道在哪儿打开？

Set `translator/enable_correction: true` in schema to enable.

**Comment by Mintimate** [comment]
这样就可以了，不过试了一下：
<img width="752" alt="image" src="https://github.com/Mintimate/oh-my-rime/assets/43734212/6c545ea4-6841-4c32-bc04-808e72b1642c">

 输入单字时候容易造成困扰，对于手机的全拼效果估计比较好

**Comment by KyoSakuyo** [comment]
![image](https://github.com/Mintimate/oh-my-rime/assets/59904064/c0ae27c9-9ed3-400c-b216-9546286fdb0d)

![image](https://github.com/Mintimate/oh-my-rime/assets/59904064/ce0b2ca1-573e-4140-a4dd-0c42d8762db7)

成功了🎉，确实对手机端的全拼会方便不少~~~
