### ISSUE TITLE
有没有大佬在ubuntu22.04下用薄荷输入法的，我这边不管ibus还是fcitx5，只要是薄荷输入法都不显示候选条，用rime自带明月拼音就正常。 

### ISSUE THREAD

**Issue by roverway** [Mintimate/oh-my-rime#56]
如题，实在不知道该如何排查了。

**Comment by Mintimate** [comment]
有可能是官方Ubuntu 22 apt源里的rime没有编译Lua进去，比可以试试看移除所有Lua试试看。一起有人遇到这个问题。

**Comment by YummyCocoa** [comment]
Ubuntu 22应该是基于 Debian 12，Debian 12的上游就有这个问题了。或许还没有解决，参考： https://forums.debiancn.org/t/topic/3836

**Comment by catvox** [comment]
看最新的评论已经解决，下载https://gitee.com/wubi98/fcitx5-98wb/releases/tag/v3.0 ，安装后替换好配置文件，把default.custom.yaml中的path自己修改一下。重新部署就OK!

**Comment by roverway** [comment]
> 有可能是官方Ubuntu 22 apt源里的rime没有编译Lua进去，比可以试试看移除所有Lua试试看。一起有人遇到这个问题。

大佬，我又试了雾凇拼音，所有lua功能（以词定字、反查、农历、日期时间等）都能正常用，但是同样的环境下，薄荷输入法就不行，所以我感觉可能还是薄荷输入法自身哪里有问题。

**Comment by Mintimate** [comment]
> > 有可能是官方Ubuntu 22 apt源里的rime没有编译Lua进去，比可以试试看移除所有Lua试试看。一起有人遇到这个问题。
> 
> 大佬，我又试了雾凇拼音，所有lua功能（以词定字、反查、农历、日期时间等）都能正常用，但是同样的环境下，薄荷输入法就不行，所以我感觉可能还是薄荷输入法自身哪里有问题。

和群友确认了，是部分Linux发行版本Fcitx5、iBus的Rime支援使用的librime版本是旧版。导致无法使用Lua引入的新语法。薄荷用的是新语法，雾凇用的是旧的，所以你的Linux无法使用薄荷。解决办法，要么手动使用新的librime编译安装rime，要么参考这次破坏性变更: https://github.com/Mintimate/oh-my-rime/commit/18e0ae7aa52773d8dd7e15a4ad15a8c91bc9e6d9 ，改回旧版Lua引入语法。

当然，等待上游库使用新版librime也可以。
