### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by mirtlecn** [Mintimate/oh-my-rime#57]
**辅码 lua**

https://github.com/Mintimate/oh-my-rime/blob/43757469d1d314deea83ee5f22e169d29c28690e/lua/auxCode_filter.lua#L28

这么写 bug，一种做法是新设置一个变量。新设置的变量只用在 find 和 match 函数中，对于：

https://github.com/Mintimate/oh-my-rime/blob/43757469d1d314deea83ee5f22e169d29c28690e/lua/auxCode_filter.lua#L64

这一行，要用原样的 key，否则输入词组会出现 % 上屏的情况。

**地球拼音拼音**

㹴读音应当是 geng1。地球拼音我记得之前修订的时候看到有其他错误，可能后续要改一改。

**地球拼音 python 脚本**

注意到用了 pypinyin 去生成带音调的词典。pypinyin 这个注音发含有大量多音字错误（详见 rime-ice 的大量修订记录）。 

具体到地球拼音，如果一个字有仅仅是音调不同的多音（如「更」（geng1，geng4），用机器注音，就会产生注音错误。

不清楚有没有什么好办法，不知道有没有可能尝试导入 pinyin-data-phrase 的数据，如果还不行，可能只能手动修订。

**拆字词典**

因为我最近尝试调整词典的权重，CI 生成的词典有时候变化很大，每次拉会有些不必要的 commit。

不太需要每日拉更新。可以每两三个月拉下，或者直接同步大版本更新即可。

修订的内容大多数用家都感觉不到

**拆字反查**

https://github.com/Mintimate/oh-my-rime/blob/43757469d1d314deea83ee5f22e169d29c28690e/rime_mint.schema.yaml#L290

这个是有意设置的吗？我记得这么写，会导致：只有打出全部的音节，才出现候选，是不是不太合适。

比如想查「水水水」，这么写，似乎会导致打「水水」不会有三个水的候选，一些构造很多的字，每次打完不太现实。

**Comment by Mintimate** [comment]
这个，我一个一个来回答一下。 
#### 辅码 lua
我直接使用`trigger_key `，其实是因为这个配置是我基于原版分词`辅码 lua`，新定义的，所以我觉得没什么问题就直接对变量处理了…… 

#### 地球拼音
这个我实际上也发现了，但是短期内实在有心无力。 只能以后在尝试了😢；单个`㹴`读音，这个倒是可以处理。

#### 拆字字库
拆字字库，我其实前几天已经调整为14天同步一次了。 下次我更改为1个月试试。`enable_completion: false `，确实不合理。 下次我改一下。

#### 请教
其实我一直想改反查，现在小鹤里`~~`来反查，其他内是`uu`；我是想用`Uu`作为反查的。 但是这样，`Uu`后无法使用数字键盘来选定候选。 所以不知道大佬有什么建议？

**Comment by Mintimate** [comment]
还是得大佬出马呀。感谢，这回应该对了。 另外，有一个小问题…… 就是我发现，全拼内如果使用简拼功能：
```yaml
speller:
  algebra:
    - abbrev/^([a-z]).+$/$1/     #简拼（首字母）
```
可以达到简拼的效果，但是这样使用正则检录那么多字词，如果输入多个字，可能会卡顿，尤其是小狼毫上最为明显（可以一直按s）测试。我目前能想到的，就是替换为：
```yaml
speller:
  algebra:
    - abbrev/^([a-z])[a-z]*$/$1/       # 简拼（首字母）
``` 
使用`[a-z]`替换通配符，可以快一点，但是不多；不知道大佬有什么思路？不知道我这次有没有描述好。

**Comment by mirtlecn** [comment]
> 尤其是小狼毫上最为明显（可以一直按s）测试。我目前能想到的，就是替换为：

好像小狼毫有个切换应用后首键（类型情形）卡顿的 bug，要是鼠须管、Fcitx 等平台没问题的话，就怪小狼毫好了。
