### ISSUE TITLE
薄荷拼音 中文状态下 不能输入半角符号

### ISSUE THREAD

**Issue by ilovesusu** [Mintimate/oh-my-rime#58]
就算 是通过快捷键切换了半角  输入后 也是全角  

写代码很不方便啊

**Comment by Mintimate** [comment]
什么意思？默认继承rime自带的symbols，全角和半角是符合一般操作习惯的。我平常写代码也没发觉有什么问题，哪一方面？

**Comment by victorzhao** [comment]
是指中文状态输入/么，这个直接配置rime的符号就可以

**Comment by lovelope** [comment]
是oh-my-rime把英文半角符号映射到中文符号了，需要手动把`default.yaml`文件的`punctuator.half_shape`整段注释掉

**Comment by 21307369** [comment]
这个问题把我给搞疯了，，问ai 也没用

**Comment by gddg** [comment]
我注释掉了
#punctuator:
#  import_preset: symbols
#  # 定义部分半角字符
#  half_shape:
#      "#": "#"
#      "*": "*"
#      '.' : { commit: 。 }
#      "`": "`"
#      "~": "~"
#      "@": "@"
#      "=": "="
#      "/": ["/", "÷",]
#      '\': "、"
#      "_" : "──"
#      "'": {pair: ["「", "」"]}
#      "[": ["【", "["]
#      "]": ["】", "]"]
#      "$": ["¥", "$", "€", "£", "¢", "¤"]
#      "<": ["《", "〈", "«", "<"]
#      ">": ["》", "〉", "»", ">"]

**Comment by gddg** [comment]
注册掉了

#punctuator:
#  import_preset: symbols
#  # 定义部分半角字符

我希望在中文，也输入法英文符号，不知道怎么弄？
