### ISSUE TITLE
如果能支持五笔86就更好了。毕竟打五笔86的可能比98的多很多

### ISSUE THREAD

**Issue by AlbertWang2018** [Mintimate/oh-my-rime#60]

**Comment by YummyCocoa** [comment]
其实，最初薄荷配置里是使用 86 的，不过后来群里说 98 多，就用98了。当时都不重要…… 重要的是，维护人员里目前没有人会五笔，导致适配有点麻烦，不知道用五笔的人，习惯怎么样。

**Comment by AlbertWang2018** [comment]
> 其实，最初薄荷配置里是使用 86 的，不过后来群里说 98 多，就用 98 了。当时都不重要…… 重要的是，维护人员里目前没有人会五笔，导致适配有点麻烦，不知道用五笔的人，习惯怎么样。

感谢回复。建议五笔86和98都加上，可以切换就行。不过对于会配置的人，增加或替换个词库文件也很容易。感谢分享。

**Comment by Mintimate** [comment]
加上86，有两个问题，一个是缺少人员维护，另外一个就是考虑词库体积了。现在薄荷维护人员里没有会五笔的，而且薄荷现在体积挺大的了。不过，主要是没有维护人员，如果愿意，欢迎提交pr

**Comment by AlbertWang2018** [comment]
> 加上 86，有两个问题，一个是缺少人员维护，另外一个就是考虑词库体积了。现在薄荷维护人员里没有会五笔的，而且薄荷现在体积挺大的了。不过，主要是没有维护人员，如果愿意，欢迎提交 pr

好的，我可以试试，我代码水平比较菜。

**Comment by Mintimate** [comment]
https://github.com/Mintimate/oh-my-rime/commit/413829d9e9f23fdc5daa41aa024713c4173128f3 已经适配[86五笔极点](https://github.com/KyleBing/rime-wubi86-jidian) 的单字版本到薄荷内，欢迎体验和基于薄荷的配置自行制定和扩展。 不过如果是86重度使用用户，我认为用[86五笔极点](https://github.com/KyleBing/rime-wubi86-jidian)仓库比较好😊。
