### ISSUE TITLE
ios可以实现中英混合输入吗？

### ISSUE THREAD

**Issue by GD2021** [Mintimate/oh-my-rime#63]
我把配置导入到仓输入法，无法实现中英混合输入，是不是不支持？

**Comment by Mintimate** [comment]
默认就是开启中英混合输入法的，如果需要更改，参考每个输入法里的以下部分： 
https://github.com/Mintimate/oh-my-rime/blob/46a070dd0dedf72725631b1c16b2d0a23ecc3112/rime_mint.schema.yaml#L77

https://github.com/Mintimate/oh-my-rime/blob/46a070dd0dedf72725631b1c16b2d0a23ecc3112/rime_mint.schema.yaml#L89

https://github.com/Mintimate/oh-my-rime/blob/46a070dd0dedf72725631b1c16b2d0a23ecc3112/rime_mint.schema.yaml#L119

https://github.com/Mintimate/oh-my-rime/blob/46a070dd0dedf72725631b1c16b2d0a23ecc3112/rime_mint.schema.yaml#L157

**Comment by GD2021** [comment]
如果您的配置更新了，我想要覆盖，如何备份我的使用习惯？具体备份哪个文件？

比如：我输入一个公司名，下次再输入时他就会记忆优先，不用再去选择，如何备份这些。

**Comment by Mintimate** [comment]
群里已经说了，不要重复提问。 

> 你覆盖文件时候选择同名覆盖，用户词典内容默认在build里，就不会有问题。 如果是覆写输入法内容，用custom文件去覆写scheme文件内容，同名覆盖也不会有问题。

**Comment by Msir20** [comment]
你好，我想要的效果是不改变中英文状态下，中英文和数字混合的连贯输入。例如：”我在7eleven里买零食“，macOS的原生中文输入法可以通过按option键中文加数字连贯的效果。
<img width="78" alt="image" src="https://github.com/user-attachments/assets/9b82ef2b-af5f-462e-aa65-d234dea2adca" />
