### ISSUE TITLE
无法输入中文

### ISSUE THREAD

**Issue by haimingz** [Mintimate/oh-my-rime#64]
几周前的版本是没问题的，最新版部署后无法输入中文（直接不显示ibus的候选窗口）

疑似[!feat: 使用default替代default.custom](https://github.com/Mintimate/oh-my-rime/commit/3bf641623b749bda57655e441b08476cc75f2182) 所致。

ubuntu 22.04

**Comment by Mintimate** [comment]
Ubuntu 22的 apt 源问题，等待上游解决、手动使用高版本 librime 编译 fcitx5-rime / iBus-rime 或者回滚 薄荷的 Lua 写法即可。 

Similar with https://github.com/Mintimate/oh-my-rime/issues/59 and https://github.com/Mintimate/oh-my-rime/issues/56 .
