### ISSUE TITLE
仓输入法怎么导入呀

### ISSUE THREAD

**Issue by subaoziya** [Mintimate/oh-my-rime#65]
仓输入法怎么导入呀

**Comment by Mintimate** [comment]
仓输入法的一键在线导入已经和作者沟通，需要等仓输入法的作者适配。不清楚还要多久。 

可以先用传统方法导入，视频教程可以查看： 【移动端安装无隐私追踪、高自定义的RIME输入法，并使用薄荷输入法模板快速初始化！-哔哩哔哩】 https://b23.tv/kTRuLkX
