### ISSUE TITLE
簡體->繁體 修正, 着->著

### ISSUE THREAD

**Issue by shdennlin** [Mintimate/oh-my-rime#66]
在中國的簡體字 `着` 對應臺灣的爲 `著`, 可以通過什麼設定去修改嗎?

**Comment by YummyCocoa** [comment]
参考 雾凇 里的这个 issue: https://github.com/iDvel/rime-ice/issues/627

也就是，用 OpenCC 把目前 st2 再转一遍就是台湾风格了。
