### ISSUE TITLE
能否设置自动在中英字符之间加入空格？

### ISSUE THREAD

**Issue by immadolf** [Mintimate/oh-my-rime#67]
Mac 上的搜狗和微信输入法都是支持这个功能，rime 有办法配置吗？我看https://github.com/rime/home/issues/24 上写了输入法本身不打算支持。

**Comment by Mintimate** [comment]
这个简单，在 filter 内使用 Lua 处理一下就可以了。 你可以参考雾凇的：https://github.com/iDvel/rime-ice/blob/main/lua/en_spacer.lua

把其中的`input:gsub("(%a+'?%a*)", "%1 ")`改为`input:gsub("(%a+'?%a*)", " %1 ")`即可。

**Comment by immadolf** [comment]
如果是这样改的话，是不是我每次打一个英文都会在前后添加空格？

**Comment by YummyCocoa** [comment]
> 如果是这样改的话，是不是我每次打一个英文都会在前后添加空格？

对，不过无意义的英文也会，语法是匹配字符。 你可以输入单词需要选中用空格或者数字进行候选。 无意义英文使用回车↩️

**Comment by immadolf** [comment]
好的 谢谢

**Comment by BTBMan** [comment]
最新版设置了这个 filter 后会导致候选条消失。
