### ISSUE TITLE
想让候选词菜单不显示多余的繁体

### ISSUE THREAD

**Issue by tyf2018** [Mintimate/oh-my-rime#68]
词库都是简体，部署薄荷里的小鹤双拼-薄荷定制方案后，候选菜单中会同时出现简体、繁体，像这样
![R ~KAC97)BBQU$(3QZL9_YU](https://github.com/Mintimate/oh-my-rime/assets/56342788/2f9f8b68-1bfd-4f38-87aa-1ecf54e8254d)
![image](https://github.com/Mintimate/oh-my-rime/assets/56342788/1baa67f5-0a57-4f05-8a41-06e12b0dcf26)

切换到别的双拼方案例如智能ABC则正常，只有简体
![image](https://github.com/Mintimate/oh-my-rime/assets/56342788/2a3aea62-474e-4cce-8d06-bf8a2b7a5a88)

请问有办法让小鹤的候选菜单只显示简体么？谢谢

**Comment by Mintimate** [comment]
无法复现：

![测试](https://github.com/Mintimate/oh-my-rime/assets/43734212/6640237a-abf5-4d06-9a16-1183e4cdf7e7)

把 build 删除后重新部署试试看。

**Comment by tyf2018** [comment]
> 把 build 删除后重新部署试试看。

删了build 重新部署，问题仍旧。很奇怪。能帮忙看下配置文件是否有问题么？

[Rimedouble_pinyin_flypy.schema.zip](https://github.com/Mintimate/oh-my-rime/files/15073960/Rimedouble_pinyin_flypy.schema.zip)

**Comment by tyf2018** [comment]
> 去除后，排查一下试试看。

问题仍旧 😂

**Comment by YummyCocoa** [comment]
那你就排查其他的部分就可以了。没有你词典内容，无法查看更多有效信息。 不过薄荷目前确实没有这个问题 @Mintimate
