### ISSUE TITLE
如何配置Linux端的皮肤？

### ISSUE THREAD

**Issue by haoxiaoyueh** [Mintimate/oh-my-rime#69]
**我按照教程里的安装的是Fcitx5，但是没有找到在哪里可以设置**

> ![image](https://github.com/Mintimate/oh-my-rime/assets/113106402/beac248b-ad27-4fd6-8bcf-cb138b93e1f4)

**我下载完上图中链接里的压缩包之后解压出来的文件是两个文件夹，虽然能看得出来分别是白天和夜晚模式的皮肤，但是这个文件夹应该放在那里令我感到迷惑。**

> ![image](https://github.com/Mintimate/oh-my-rime/assets/113106402/8fc9e8e1-7284-4834-9a66-74b5ea30e992)

**我找到了配置文件里的这段，如下图：**

> ![image](https://github.com/Mintimate/oh-my-rime/assets/113106402/58349a4a-d6a1-4e92-bec1-2ac3eb1c2726)

**然后我在Rime配置文件夹里只找到了这两张图片是和配置文件里的名称比较相似的：**

> ![image](https://github.com/Mintimate/oh-my-rime/assets/113106402/b71123d9-c3ab-43b6-9534-73f384aa06e9)

我想知道怎么配置这两个文件夹，或者如果Linux安装的Fcitx5不支持的话，希望能予以兼容。

**Comment by Mintimate** [comment]
已支持 Fcitx5 rime ，框架皮肤问题可以看 Fcitx5 文档，或者别人已有的经验。如： https://bbs.deepin.org/phone/zh/post/223810

**Comment by hanmingk** [comment]
@Mintimate 请问Linux gnome主题用的是哪个阿？

**Comment by Mintimate** [comment]
> 
> 
> @Mintimate 请问Linux gnome主题用的是哪个阿？

取决于你用什么输入法引擎，和桌面GUI无关

**Comment by hanmingk** [comment]
> > @Mintimate 请问Linux gnome主题用的是哪个阿？
> 
> 取决于你用什么输入法引擎，和桌面GUI无关

我是觉得你的桌面主题挺好看的，所以才问你主题，不是说输入法皮肤

**Comment by Mintimate** [comment]
> > > @Mintimate 请问Linux gnome主题用的是哪个阿？
> 
> > 
> 
> > 取决于你用什么输入法引擎，和桌面GUI无关
> 
> 
> 
> 我是觉得你的桌面主题挺好看的，所以才问你主题，不是说输入法皮肤

kali默认。不要在在一个issue主题内发送无关内容啊
