### ISSUE TITLE
请问Android端如何才能正确激活小鹤方案的音形功能？

### ISSUE THREAD

**Issue by tyf2018** [Mintimate/oh-my-rime#70]
我的Android手机安装了小企鹅输入法，部署了薄荷方案中的小鹤双拼（音形），大部分功能正常使用。现在遇到一个问题：我想使用小鹤方案中的音形功能，但Android的虚拟键盘中并无 单独的`;`鍵来激活音形功能。

尝试将`;`键改成`.`键，未果。
![image](https://github.com/Mintimate/oh-my-rime/assets/56342788/6b223cb7-43cd-434d-9d1c-43bfc49668ec)
![image](https://github.com/Mintimate/oh-my-rime/assets/56342788/03125b84-4f15-4aaa-9a05-08275f79c4b4)

请问应该如何解决呢？谢谢

**Comment by Mintimate** [comment]
“如果想切换激活辅助码的按键，可以使用custom覆写 double_pinyin_flypy.schema.yaml 的axu_code，并且speller内的alphabet追加新的辅助激活码。”

上述内容在薄荷文档内已经说明，不再赘述： https://www.mintimate.cc/zh/demo/doublePinyinFly.html

**Comment by tyf2018** [comment]
按此法修改，未达预期效果才来提问的。
薄荷方案未做任何修改，只新增了一个custom文件如下：
[double_pinyin_flypy.custom.zip](https://github.com/Mintimate/oh-my-rime/files/15103729/double_pinyin_flypy.custom.zip)

修改后，按`.`键能切换出辅助码，但继续按键，目标候选字的位置无任何变动。如下图所示，按下`.`键，再继续按`pa`键，`册`字仍然排在第三位，而不是首位
![【竖向拼接】Screenshot_20240425_113001_com ghisler android TotalCommander](https://github.com/Mintimate/oh-my-rime/assets/56342788/bbb8f0f9-eed3-431e-881e-e87ebbe3f38d)

能否帮忙看下问题出在哪？谢谢

**Comment by YummyCocoa** [comment]
试了一下，是 auxCode.lua 里转义问题，把：
```lua
local trigger_pattern = env.trigger_key_string:gsub("%W", "%%%1") -- 處理特殊字符
```
替换为 ：
```lua
local trigger_pattern =  env.trigger_key_string
```
就可以了。 估计是之前 @Mintimate 写了 `alt_lua_punc` 方法修复上部分 bug 后，后面这些漏了。

**Comment by tyf2018** [comment]
> 就可以了。 估计是之前 @Mintimate 写了 `alt_lua_punc` 方法修复上部分 bug 后，后面这些漏了。

太感谢了！问题已解决！
