### ISSUE TITLE
Windows右下角图标的建议

### ISSUE THREAD

**Issue by xnuxmwx** [Mintimate/oh-my-rime#73]
Windows右下角的图标，英文状态都是个A，能让它小写是E，大写是A吗？不管用什么字母只要能区分出来就好。我现在为了区分大小写单独安装了一下Capslock软件。

**Comment by Mintimate** [comment]
这个属于小狼毫的问题了，英文状态图标应该目前是可以，可以查看 https://github.com/rime/weasel/pull/882 。

至于大写情况下和不大写情况使用不同的图标，这个记得是不行的。 或许你可以在小狼毫仓库内提 issue 。
