### ISSUE TITLE
f 字母的第二个选词是什么情况？

### ISSUE THREAD

**Issue by WUST-mengqinyu** [Mintimate/oh-my-rime#74]
![image](https://github.com/Mintimate/oh-my-rime/assets/45025194/4dd639af-901d-440e-9e9e-c6fde728ef1a)

看了下拷出来是 𡉚 字符

**Comment by Mintimate** [comment]
你字库没这个字：

<img width="965" alt="image" src="https://github.com/Mintimate/oh-my-rime/assets/43734212/e0f4a20b-1c16-459b-a00d-7bd55ec7234d">

系统安装大字库或者移除 41448字库： https://github.com/Mintimate/oh-my-rime/blob/bf7a4e3eac2af958ba551e3638faeb9c4e164e70/rime_mint.dict.yaml#L10
