### ISSUE TITLE
[问题反馈] Zorin OS 17.1等 Linux 上，无法使用薄荷输入配置输入？

### ISSUE THREAD

**Issue by XuJinNet** [Mintimate/oh-my-rime#75]
在 Zorin OS 17.1 上安装了 ibus-rime 后可以正常输入，但拷贝了薄荷输入法配置到  `.~/config/ibus/rime/` 目录并部署后，输入拼音时没有任何候选词显示。请教可以怎样解决？
![image](https://github.com/Mintimate/oh-my-rime/assets/442382/ba6c6226-ebb7-4684-b98b-8df2b2607894)

**Comment by Mintimate** [comment]
Same with: https://github.com/Mintimate/oh-my-rime/issues/56
