### ISSUE TITLE
Linux fcitx5 rime 薄荷拼音禁止文字后面显示拼音

### ISSUE THREAD

**Issue by Eason-YC-Huang** [Mintimate/oh-my-rime#77]
您好，请问要在哪里进行配置可以关闭拼音显示功能？输入拼音后，它会显示字体，默认字体后面会显示拼音，我想禁用这个行为。

Hi, may I know how to disable the Pinyin displays after the Chinese on the input box?

**Comment by Mintimate** [comment]
怎么说？ 截图我看看？

**Comment by Eason-YC-Huang** [comment]
![image](https://github.com/Mintimate/oh-my-rime/assets/40693388/f69a99db-da8a-4ffc-bb37-4d69e98110f6)

在网上搜索了一翻，说是没有安装librime-lua导致，我尝试使用apt install librime-lua来安装这玩意，但是不行。
然后按照它的教程编译，编译报错，不怎么会cmake，一头雾水。

我目前用的是薄荷输入法 全拼，我没别的改动，就是换了个皮肤。

我目前用的是deepin v23

**Comment by Mintimate** [comment]
换 fcitx5 框架，并且更换为 fcitx5-rime 版本的 rime

**Comment by Eason-YC-Huang** [comment]
还是不行，还是用回debian 去了

**Comment by Mintimate** [comment]
记得 deepin 也是基于 Debian 的，只是 apt 源有所不同，可以多试试看。

我的 Linux 发行版本是 kali 也是基于 Debian 的，目前就可以。

但是其他人反馈，Ubuntu 20 前段时间 apt 内使用的旧版本 librime，导致 Fcitx5 rime 无法使用薄荷的 lua 扩展，要么手动编译安装，要么等上游 apt 更新了😮‍💨

**Comment by carica** [comment]
在用基于fcitx4的librime 1.2，是否要删除把所有的lua部分都删除呢

**Comment by ericoff2022** [comment]
Fedora 42 测试:
安装 librime-lua 以后输入文字, 仍然在候选后面出现拼音.
考虑可能是 fcitx5 需要重启的问题, 输入 fcitx5 -r 然后输入中文, 仍然未解决问题.
另考虑可能是没有重新部署 rime 
重新部署 rime 测试,输入中文, 解决问题.
整体过程没有做"消融实验", 不过可能是没有重新部署的问题.
