### ISSUE TITLE
如何启用小鹤音形

### ISSUE THREAD

**Issue by cheneyjuu** [Mintimate/oh-my-rime#78]
看文档“小鹤双拼-薄荷定制”是支持音形输入的，但是我尝试了一下，发现无法使用形码，是还需要什么设置吗？还是使用姿势不对？

**Comment by Mintimate** [comment]
薄荷内的小鹤音形是作为辅码辅助双拼定位的。具体使用可以参考：
- https://www.mintimate.cc/zh/demo/doublePinyinFly.html
- https://github.com/HowcanoeWang/rime-lua-aux-code

**Comment by transread** [comment]
请问 如何将唤醒键设置成 tab 键？

**Comment by Mintimate** [comment]
> 请问 如何将唤醒键设置成 tab 键？

不太行，像tab和enter这样本来就有特殊功能的，应该不行。

**Comment by transread** [comment]
> > 请问 如何将唤醒键设置成 tab 键？
> 
> 不太行，像tab和enter这样本来就有特殊功能的，应该不行。

那如何不使用辅助激活码“ ；”，直接引导辅助码呢？

**Comment by transread** [comment]
现在的问题是，设置别的键──如grove键“`”──为辅助码激活键，输出会出现问题。

如我想输出 ji fa，不使用辅助码时，排名第一的候选词是「激发」，当我使用「`」激活辅助码，选好了「姬发」时，还是会输出第一候选词「激发」。
