### ISSUE TITLE
小鹤双拼的模糊拼音一直有问题

### ISSUE THREAD

**Issue by qkxie** [Mintimate/oh-my-rime#83]
已经根据文档里面的说明，修改rime_mint.schema.yaml并重新部署了：

![image](https://github.com/Mintimate/oh-my-rime/assets/134578340/832a548a-61a2-4e47-98a1-875aa1f9040f)

但是使用平舌音『slpk』根本打不出『双拼』这两个字。sl打不出『双』，pk打不出拼。yk也打不出音。

目前我测试过无数的Rime + 小鹤双拼方案，所有方案的模糊拼音全都有问题。

**Comment by Mintimate** [comment]
测试了一下，不存在这个问题，检查自己设置。

![测试模糊拼音](https://github.com/Mintimate/oh-my-rime/assets/43734212/55b92eb4-d0fe-45da-9999-0378bfd185c9)

**Comment by qkxie** [comment]
小鹤双拼-薄荷定制，修改的文件应该是double_pinyin_flypy.schema.yaml吧。

**Comment by Mintimate** [comment]
对。最好用custom去覆写。
