### ISSUE TITLE
请问 rime_mint.dict.yaml 里面补充的词库，词频应该怎么设置？

### ISSUE THREAD

**Issue by haolly** [Mintimate/oh-my-rime#84]
最大值，最小值之类的设置
现在遇到的问题就是，我自己的搜狗个人词库用深蓝转换之后补充到 custom 里面去，但是因为导出的搜狗的词频最高的也才两三百而已，导致搜狗里面经常输入的词其实被排在了最后面，因为 rime_ice.8105 里面的词频都是十几万的值

所以，同一本词典里面的词频相对来说是合理的，但是不同词典之间的词频对比就不合理了，不知道我有没有描述清楚这个问题 🤔 
想问下这种有没有啥比较好的办法解决呢？

**Comment by Mintimate** [comment]
拼音词库使用雾凇拼音的，具体要看雾凇拼音如何处理，不过我觉得目前拼音词库用着很不错了： [https://github.com/iDvel/rime-ice](https://github.com/iDvel/rime-ice)

**Comment by Mintimate** [comment]
不过想了一下。你可以批量把自己的搜狗词库词频提供，比如直接提高为几万，使其比雾凇的高。 或者对自己的词库足够满意，可以剔除雾凇词库，使用自己的词库。

**Comment by haolly** [comment]
简单粗暴提高几万是不行的，可能过大也可能过小，不同词典的权重要有一个统一的标准才行。
不过算了吧，我又用回搜狗了，用了几天rime发现打字效率直线下降 😢   而且rime作者对于我提的问题也不认同，基本没法改善了

**Comment by anaer** [comment]
个人词库可以通过用户词典管理导入到用户词典, 相对扩展词库来说 应该优先级会高些
