### ISSUE TITLE
文字亂碼

### ISSUE THREAD

**Issue by leohkz** [Mintimate/oh-my-rime#86]
習慣用普通話拼音打粵語字，在輸入框有些字出現方框問號，請問可以怎麼解決？
是字體問題嗎？

![CleanShot 2024-05-11 at 09 32 26@2x](https://github.com/Mintimate/oh-my-rime/assets/30283225/5b492c2e-4e87-4dea-89c6-64c09ef66cdc)

**Comment by Mintimate** [comment]
问题和这个一样： https://github.com/Mintimate/oh-my-rime/issues/74

可以安装大字库或者移除41448字库。 大字库，推荐可以用：
- [花园明朝](https://glyphwiki.org/hanazono/)
- [小米MiSans L3](https://hyperos.mi.com/font/rare-word)
- [落霞文楷](https://github.com/lxgw/LxgwWenKai)
