### ISSUE TITLE
请问我在使用t9的时候，是没有单独的字典文件么。另外custom phrase t9.txt这个文件是放在哪里呢

### ISSUE THREAD

**Issue by bandengzex** [Mintimate/oh-my-rime#88]
![255a71db52ce8f59ce762e3e065a42ad](https://github.com/Mintimate/oh-my-rime/assets/103732230/2dacf870-4054-460d-a8b7-9cbc483b1a97)

**Comment by Mintimate** [comment]
项目目录内新建，这个就是普通用户短语。如果你要放在dicts目录下，就改为 dicts/开头
