### ISSUE TITLE
emoji无法正确被关闭

### ISSUE THREAD

**Issue by Mini-Jelly** [Mintimate/oh-my-rime#89]
emoji关闭后在输入法候选中仍然存在emoji候选，opencc的文件也修改了，相关的emoji_suggestion全都注释
![2024-05-14_00-14-17](https://github.com/Mintimate/oh-my-rime/assets/66431219/bb78cd43-8db1-4b39-933f-894e5d0f16ad)
 
![2024-05-14_09-41-45](https://github.com/Mintimate/oh-my-rime/assets/66431219/4a72ed4f-d893-43d3-96a1-03ec2c647b8c)

**Comment by Mini-Jelly** [comment]
使用的window10
![2024-05-14_09-42-38](https://github.com/Mintimate/oh-my-rime/assets/66431219/124f24de-d654-4ea1-9c09-e44e0b5ca71e)

**Comment by Mintimate** [comment]
移除Emoji补充词典：https://github.com/Mintimate/oh-my-rime/blob/40c947fb4906cbe032e936199b5c26a96d46a77a/rime_mint.dict.yaml#L14

**Comment by Mini-Jelly** [comment]
无敌了，[文档](https://www.mintimate.cc/zh/guide/openccEmoji.html)记得更新哦[狗头]

**Comment by Mintimate** [comment]
文档看情况，没人看，已经没有更新必要。本身薄荷内注释已经很完整了，同样没人看而已。
