### ISSUE TITLE
开启模糊音后能显示正确拼音吗？

### ISSUE THREAD

**Issue by HenryLau0220** [Mintimate/oh-my-rime#91]
# 问题
开启模糊音后，能否显示字词正确的拼音，类似于错音错字提示一样：
![image](https://github.com/Mintimate/oh-my-rime/assets/70014887/2d55215d-21e6-4bcd-a7b6-7a872eed7a65)
我想要的效果是输入“ping ying"后显示”拼音 pin yin"这样的。
我搜到相同的[问题](https://github.com/rime/home/issues/661)，但是不起作用😣：
![image-20240515204541667](https://github.com/Mintimate/oh-my-rime/assets/70014887/10acc44c-9fb9-4d12-942d-edc7ab180bc3)
# 配置情况(double_pinyin_flypy.schema.yaml)：
```yaml
translator/spelling_hints: 8
speller/algebra:
    - erase/^xx$/
    - derive/^([zcs])h/$1/ # zh, ch, sh => z, c, s
    - derive/^([zcs])([^h])/$1h$2/ # z, c, s => zh, ch, sh
    - derive/([aei])n$/$1ng/ # en => eng, in => ing
    - derive/([aei])ng$/$1n/ # eng => en, ing => in
    - derive/l/n/
    - derive/n/l/
    ...
```

**Comment by HenryLau0220** [comment]
谢谢回复，我懂了。不过注释`lua_filter@*corrector_filter`这行会让正确的词也显示出拼音：
![image](https://github.com/Mintimate/oh-my-rime/assets/70014887/73418fc0-b535-42a6-85d3-4cbeeffe1bd4)
看来是要自定义一个lua脚本。

**Comment by syn0289** [comment]
> 谢谢回复，我懂了。不过注释`lua_filter@*corrector_filter`这行会让正确的词也显示出拼音：
> 
> ![image](https://github.com/Mintimate/oh-my-rime/assets/70014887/73418fc0-b535-42a6-85d3-4cbeeffe1bd4)
> 
> 看来是要自定义一个lua脚本。

大佬，我也遇到和你一样的问题。纠错和提示能兼得吗？

**Comment by Mintimate** [comment]
> > 谢谢回复，我懂了。不过注释`lua_filter@*corrector_filter`这行会让正确的词也显示出拼音：
> > 
> > ![image](https://github.com/Mintimate/oh-my-rime/assets/70014887/73418fc0-b535-42a6-85d3-4cbeeffe1bd4)
> > 
> > 看来是要自定义一个lua脚本。
> 
> 大佬，我也遇到和你一样的问题。纠错和提示能兼得吗？

可以呀，在 corrector_filter.lua 里改改应该可以。具体可以试试看。

**Comment by chunsing128** [comment]
> 具体

大佬 你实现这个功能了吗

**Comment by Mintimate** [comment]
> > 具体
> 
> 大佬 你实现这个功能了吗

这个实现很简单，只是感觉没必要。如果你现阶段想实现，移除：
https://github.com/Mintimate/oh-my-rime/blob/6a0e77c3aadf71e8a639366100791e4a123ee0f5/lua/corrector_filter.lua#L131-L132

重新部署即可：
![实现效果](https://github.com/user-attachments/assets/628421ab-dd5e-4ba2-9475-02df39888b71)

**Comment by PillarsZhang** [comment]
目前这种实现还是会显示正确词的拼音，要还原 Rime 默认功能 **preedit 等于 comment 时取消显示 comment** 注释掉 `rime_mint.schema.yaml` 文件 `engine/filters` 中的 `lua_filter@*corrector_filter`，修改 `rime_mint.custom.yaml`：
```yaml
patch:
  translator/always_show_comments: false  # Rime 默认在 preedit 等于 comment 时取消显示 comment
  translator/comment_format: [] # 标记拼音注释
```
缺点是 `corrector_filter` 的功能就关闭了（虽然感觉用处本身不大），但即使这样只有 preedit **完全等于** comment 时注释才被隐藏，显示注释的频率还是太高了

![图片](https://github.com/user-attachments/assets/eeaead98-56b6-452c-8315-1d0baf279ed5)
![图片](https://github.com/user-attachments/assets/ef5ae305-6971-4d53-aad4-fcb492b2a51f)
![图片](https://github.com/user-attachments/assets/98da6c66-7b29-4305-ae3f-ed0d6e44f541)

---

我的目标是，本身不构成“纠错”的，只是局部或简写被匹配的，不应该显示注释，看起来不错

![图片](https://github.com/user-attachments/assets/8714f88e-a2ea-40c6-a9b2-46ff6048bd9f)
![图片](https://github.com/user-attachments/assets/f6bf01c4-04ad-4707-8758-3d36c9923311)
![图片](https://github.com/user-attachments/assets/b1248047-da4e-420b-807f-3fc7d415d9f6)

首先在原始配置基础上，设置`rime_mint.custom.yaml` 中 `corrector_filter/keep_source_comment: true`，然后修改 [`corrector_filter.lua`](https://github.com/Mintimate/oh-my-rime/blob/a7545a69a4e4912929e22e2a81d1b63b38a84403/lua/corrector_filter.lua) 如下：
```lua
-- 分割字符串
local function split(input, sep)
    local result = {}
    for part in input:gmatch("([^" .. sep .. "]+)") do
        table.insert(result, part)
    end
    return result
end

-- 分割拼音并比较是否每一项的开头部分一致
local function is_correction(correct, preedit, delimiter)
    local correct_parts = split(correct, delimiter)
    local preedit_parts = split(preedit, delimiter)
    for i = 1, math.min(#correct_parts, #preedit_parts) do
        if not correct_parts[i]:find("^" .. preedit_parts[i]) then
            return true
        end
    end
    return false
end

function M.func(input, env)
    for cand in input:iter() do
        -- cand.comment 是目前输入的词汇的完整拼音
        local pinyin = cand.comment:match("^［(.-)］$")
        if pinyin and #pinyin > 0 then
            if env.delimiter then
                pinyin = pinyin:gsub(env.delimiter,' ')
            end
            local c = M.corrections[pinyin]
            if c and cand.text == c.text then
                cand:get_genuine().comment = string.gsub(M.style, "{comment}", c.comment)
            else
                -- 20241002 是否保持原本注释；如: 拼音
                -- 20241215 如果不包含模糊拼音的矫正，依然删除注释
                local correct_pinyin = cand.comment:match("^［(.-)］$")
                local preedit_pinyin = cand.preedit
                local correction = is_correction(correct_pinyin, preedit_pinyin, env.delimiter)
                -- cand:get_genuine().comment = string.format("c:%s|p:%s|%s", correct_pinyin, preedit_pinyin, correction and "Y" or "N")
                if M.keep_source_comment and correction then
                    cand:get_genuine().comment = string.gsub(M.style, "{comment}", correct_pinyin)
                else
                    cand:get_genuine().comment = ""
                end
            end
        end
        yield(cand)
    end
end
```

第一天正式接触Rime和lua，如果有更简洁的方法欢迎指出😊

**Comment by Endif12** [comment]
> 目前这种实现还是会显示正确词的拼音，要还原 Rime 默认功能 **preedit 等于 comment 时取消显示 comment** 注释掉 `rime_mint.schema.yaml` 文件 `engine/filters` 中的 `lua_filter@*corrector_filter`，修改 `rime_mint.custom.yaml`：
> 
> patch:
>   translator/always_show_comments: false  # Rime 默认在 preedit 等于 comment 时取消显示 comment
>   translator/comment_format: [] # 标记拼音注释
> 缺点是 `corrector_filter` 的功能就关闭了（虽然感觉用处本身不大），但即使这样只有 preedit **完全等于** comment 时注释才被隐藏，显示注释的频率还是太高了
> 
> ![图片](https://github.com/user-attachments/assets/eeaead98-56b6-452c-8315-1d0baf279ed5) ![图片](https://github.com/user-attachments/assets/ef5ae305-6971-4d53-aad4-fcb492b2a51f) ![图片](https://github.com/user-attachments/assets/98da6c66-7b29-4305-ae3f-ed0d6e44f541)
> 
> 我的目标是，本身不构成“纠错”的，只是局部或简写被匹配的，不应该显示注释，看起来不错
> 
> ![图片](https://github.com/user-attachments/assets/8714f88e-a2ea-40c6-a9b2-46ff6048bd9f) ![图片](https://github.com/user-attachments/assets/f6bf01c4-04ad-4707-8758-3d36c9923311) ![图片](https://github.com/user-attachments/assets/b1248047-da4e-420b-807f-3fc7d415d9f6)
> 
> 首先在原始配置基础上，设置`rime_mint.custom.yaml` 中 `corrector_filter/keep_source_comment: true`，然后修改 [`corrector_filter.lua`](https://github.com/Mintimate/oh-my-rime/blob/a7545a69a4e4912929e22e2a81d1b63b38a84403/lua/corrector_filter.lua) 如下：
> 
> -- 分割字符串
> local function split(input, sep)
>     local result = {}
>     for part in input:gmatch("([^" .. sep .. "]+)") do
>         table.insert(result, part)
>     end
>     return result
> end
> 
> -- 分割拼音并比较是否每一项的开头部分一致
> local function is_correction(correct, preedit, delimiter)
>     local correct_parts = split(correct, delimiter)
>     local preedit_parts = split(preedit, delimiter)
>     for i = 1, math.min(#correct_parts, #preedit_parts) do
>         if not correct_parts[i]:find("^" .. preedit_parts[i]) then
>             return true
>         end
>     end
>     return false
> end
> 
> function M.func(input, env)
>     for cand in input:iter() do
>         -- cand.comment 是目前输入的词汇的完整拼音
>         local pinyin = cand.comment:match("^［(.-)］$")
>         if pinyin and #pinyin > 0 then
>             if env.delimiter then
>                 pinyin = pinyin:gsub(env.delimiter,' ')
>             end
>             local c = M.corrections[pinyin]
>             if c and cand.text == c.text then
>                 cand:get_genuine().comment = string.gsub(M.style, "{comment}", c.comment)
>             else
>                 -- 20241002 是否保持原本注释；如: 拼音
>                 -- 20241215 如果不包含模糊拼音的矫正，依然删除注释
>                 local correct_pinyin = cand.comment:match("^［(.-)］$")
>                 local preedit_pinyin = cand.preedit
>                 local correction = is_correction(correct_pinyin, preedit_pinyin, env.delimiter or " ")
>                 -- cand:get_genuine().comment = string.format("c:%s|p:%s|%s", correct_pinyin, preedit_pinyin, correction and "Y" or "N")
>                 if M.keep_source_comment and correction then
>                     cand:get_genuine().comment = string.gsub(M.style, "{comment}", correct_pinyin)
>                 else
>                     cand:get_genuine().comment = ""
>                 end
>             end
>         end
>         yield(cand)
>     end
> end
> 第一天正式接触Rime和lua，如果有更简洁的方法欢迎指出😊

我这边还是会无视我有意的简写，比如我输入nih，“你好”还是会被注释为nihao

**Comment by Endif12** [comment]
对了，接上，我的输入习惯是要么一个字完整的拼音输入，要么只输入首字母，不会输入到一半，比如“上”，我会输入shang或者s，不会输入sh

**Comment by Endif12** [comment]
目前的bug是输入zcs开头的且用单个字母组词的话，候选词会将没必要注释的内容给注释了，比如输入“zg”（这个），单字本来不需要注释，但是都给注释了，或者输入swyc（算无遗策），三文鱼也会被注释。
