### ISSUE TITLE
自定义词语

### ISSUE THREAD

**Issue by hzysoft** [Mintimate/oh-my-rime#93]
当使用【小鹤双拼-薄荷定制】方案的时候，
在custom_simple.dict.yaml文件中添加了自定义词语
其中，添加的格式为：词语(tab)拼音(tab)权重

# 常用语
哈哈	ha ha	99
macOS	mac	99
可以	ke yi	99
深圳市南山区科技园TCL大厦	di zhi	99

重新部署
并没有生效

请教大师们，如何解决？
![image](https://github.com/Mintimate/oh-my-rime/assets/1628323/f1627a9c-2bc8-48c5-b5aa-cd0ee23cdb60)

**Comment by Mintimate** [comment]
换一个可以显示Tab的编辑器，很多编辑器会优化Tab为空格。

**Comment by hzysoft** [comment]
好的，感谢，应该是权重的问题，翻到第三页才看到
