### ISSUE TITLE
ubuntu下打字出现很多方块

### ISSUE THREAD

**Issue by redhair4740** [Mintimate/oh-my-rime#94]
![QQ20240525-232116](https://github.com/Mintimate/oh-my-rime/assets/86517331/d28b9f4e-5647-42f0-aa4e-3bb1e2b34025)
如图所示，是否是缺少字体呢？

**Comment by Mintimate** [comment]
没错，就是缺少字库了。你可以看看这个看得到没有： 蝦𨉣

**Comment by redhair4740** [comment]
@Mintimate 缺的是哪个字体库呢，我目前系统是可以显示蝦𨉣的，但是rime就是显示不出来

**Comment by redhair4740** [comment]
@Mintimate 系统和rime都可以打出来蝦𨉣这两个字的，但是xia里面也是很多方块，感觉会不会是emoji？

**Comment by Mintimate** [comment]
你把`niu`里的字都打出来试试看，我看看能不能看到。或者你看这些：䤔䮗怓莥𣲶𨷁𩙷𩈇

**Comment by redhair4740** [comment]
你打的八个字，前四个我可以看到，后四个不行，𨋀𨙺𨳞𨷁𩈇𩙷𩚖𩜷𩲍这九个我这显示是方块，不知道你那是啥

**Comment by Mintimate** [comment]
那确实是字库问题，是这些：
<img width="983" alt="image" src="https://github.com/Mintimate/oh-my-rime/assets/43734212/dea1cf3b-1933-42a4-abc9-eedc40642661">

<img width="127" alt="image" src="https://github.com/Mintimate/oh-my-rime/assets/43734212/d3368049-7f2f-4304-b64a-283285d7d6d2">

**Comment by redhair4740** [comment]
解决了。花园明朝体和思源宋体，两个都安装后重启就可以了。
