### ISSUE TITLE
有关force_gc.lua

### ISSUE THREAD

**Issue by Hodwe** [Mintimate/oh-my-rime#95]
请问force_gc.lua如果想使用rime.lua实现，不通过schema的*实现，那么在schema方案和rime.lua里面应该分别怎么写，谢谢

**Comment by YummyCocoa** [comment]
参考薄荷文档的这一个部分： [Linux薄荷配置无法使用?（高版本 rime-lua 特性回退）](https://www.mintimate.cc/zh/guide/faQ.html#linux%E8%96%84%E8%8D%B7%E9%85%8D%E7%BD%AE%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8)

**Comment by Hodwe** [comment]
谢谢，但是里面好像没有force_gc.lua的设置，不太会，抱歉

**Comment by Hodwe** [comment]
主要是其他的lua可以尝试看配置的对不对，这个lua不知道失败的效果，没法尝试

**Comment by YummyCocoa** [comment]
声明GCC回收而已，测试不出来的。或者你可以自己改Lua，去写个什么文件之类的。

**Comment by Hodwe** [comment]
我看你的配置里已经有这个lua配置了，就想问问：
如果想使用rime.lua实现，不通过schema的*实现，那么在schema方案和rime.lua里面应该分别怎么写
没事，不好写的话我自己琢磨一下，谢谢了

**Comment by Mintimate** [comment]
> 参考薄荷文档的这一个部分： [Linux薄荷配置无法使用?（高版本 rime-lua 特性回退）](https://www.mintimate.cc/zh/guide/faQ.html#linux%E8%96%84%E8%8D%B7%E9%85%8D%E7%BD%AE%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8)

这里就是答案，看里面内容改就可以啊。要把每一种lua都枚举么？ 如果是这个gc的话，按教程内容就是： 

rime.lua内定义：
```lua
select_character = require("force_gc")
```

方案内`- lua_translator@*force_gc`改`- lua_translator@force_gc`

请多看看薄荷文档。现在开发成员已经都不想更新文档了，原因就是每次都没人看。

**Comment by Hodwe** [comment]
谢谢
